const LAB_DATA = {
  settings:{freeLimit:5,premiumPrice:2200,paystackPublicKey:"pk_test_YOUR_KEY"},
  units:[
    {id:"hematology",name:"Hematology",analyses:[
      {id:"pcv",title:"Packed Cell Volume (PCV)",intro:"PCV measures the volume of red blood cells expressed as a percentage of total blood volume. It is used to assess anemia, polycythemia and dehydration.",aim:"To determine the percentage of red blood cells in whole blood.",principles:"Anticoagulated blood is centrifuged at high speed. Red cells pack at the bottom. The ratio of packed cells to total blood gives PCV.",materials:["EDTA blood sample","Microhematocrit tubes","Clay sealant","Microhematocrit centrifuge","Reader"],procedure:["Mix blood well","Fill tube 3/4 and seal end","Centrifuge at 10,000rpm for 5min","Read PCV with reader"],result:"Red cell column as % of total column",normal:"Male: 40-54%. Female: 37-47%",safety:["Wear PPE","Dispose sharps","Decontaminate area"],tips:"Rule of 3: Hb x 3 ≈ PCV. Low PCV = anemia. High PCV = dehydration."},
      {id:"hb",title:"Hemoglobin Estimation - Sahli Method",intro:"Hemoglobin carries oxygen. Sahli method converts Hb to acid hematin and color is matched.",aim:"To estimate hemoglobin concentration.",principles:"Hb + HCl → Acid hematin. Color intensity compared to standard.",materials:["Sahli apparatus","N/10 HCl","Hb pipette","Distilled water"],procedure:["Put HCl to 20 mark","Add 20μL blood","Wait 10min","Add water till color match","Read g/dL"],result:"g/dL directly from tube",normal:"Male:13.5-17.5 Female:12-15.5",safety:["Handle HCl carefully"],tips:"Wait full 10min. Rushing gives low result."},
      {id:"esr",title:"Erythrocyte Sedimentation Rate",intro:"ESR measures rate RBCs settle in 1hr. Increased in inflammation.",aim:"To measure ESR.",principles:"Inflammatory proteins cause RBC aggregation and faster settling.",materials:["Westergren tube","ESR stand","Sodium citrate blood"],procedure:["Dilute blood 4:1 with citrate","Fill to 200mm","Stand 1hr","Read mm"],result:"mm/hr",normal:"M:<15 F:<20",safety:["Universal precautions"],tips:"Non-specific test. Used to monitor disease activity."},
      {id:"twbc",title:"Total White Blood Cell Count",intro:"Counts all WBCs. Elevated in infection, leukemia.",aim:"To determine WBC count per μL.",principles:"Blood diluted 1:20, WBCs counted in Neubauer chamber.",materials:["WBC pipette","Turks fluid","Counting chamber"],procedure:["Dilute blood","Load chamber","Count 4 squares","Calculate x50"],result:"Cells/μL",normal:"4000-11000",safety:["Wear gloves"],tips:"Turks lyses RBCs and stains WBC nuclei."},
      {id:"platelet",title:"Platelet Count",intro:"Platelets aid clotting. Low causes bleeding.",aim:"To count platelets.",principles:"Blood diluted 1:100, counted in chamber.",materials:["Platelet pipette","Rees-Ecker fluid","Chamber"],procedure:["Dilute","Load","Count 5 squares","x1000"],result:"/μL",normal:"150000-450000",safety:["Avoid aerosols"],tips:"Clumping causes false low."},
      {id:"diff",title:"Differential WBC Count",intro:"Percentage of each WBC type.",aim:"To identify WBC types.",principles:"Stained film examined, 100 cells counted.",materials:["Slides","Leishman stain","Oil immersion"],procedure:["Make film","Stain","Count 100 WBCs"],result:"% Neut, Lymph, Mono, Eos, Baso",normal:"N:40-75 L:20-45",safety:["Handle slides"],tips:"Good film = good diff."},
      {id:"film",title:"Peripheral Blood Film",intro:"Assesses RBC, WBC, Platelet morphology.",aim:"To prepare quality blood film.",principles:"Thin spread of blood for microscopy.",materials:["2 slides","Blood","Stain"],procedure:["Drop blood","Spread at 45°","Air dry","Stain"],result:"Thin film with feather edge",normal:"N/A",safety:["No mouth pipetting"],tips:"Feather edge must be smooth."},
      {id:"retic",title:"Reticulocyte Count",intro:"Young RBCs. Shows marrow activity.",aim:"To count retics.",principles:"New methylene blue stains RNA reticulum.",materials:["New methylene blue","Tube","Slides"],procedure:["Mix 1:1","Incubate 15min","Make film","Count 1000 RBCs"],result:"%",normal:"0.5-2.5%",safety:["Dye stains"],tips:"High in hemolytic anemia."},
      {id:"bt",title:"Bleeding Time",intro:"Tests platelet and capillary function.",aim:"To measure bleeding time.",principles:"Standard incision, time to stop.",materials:["Lancet","Filter paper","Timer"],procedure:["Clean ear","3mm incision","Blot 30s","Stop when dry"],result:"Minutes",normal:"2-9min",safety:["Sharps disposal"],tips:"Prolonged in thrombocytopenia."},
      {id:"ct",title:"Clotting Time",intro:"Intrinsic pathway function.",aim:"To measure clotting time.",principles:"Blood in glass tube clots.",materials:["Glass tube","37°C bath","Lancet"],procedure:["Collect blood","Place in bath","Tilt 30s","Note clot"],result:"Minutes",normal:"5-10min",safety:["Blood handling"],tips:"Prolonged in hemophilia."}
    ]},
    {id:"chemistry",name:"Clinical Chemistry",analyses:[
      {id:"glucose",title:"Blood Glucose",intro:"Measures blood sugar. Key in diabetes.",aim:"To estimate glucose.",principles:"Glucose oxidase → H2O2 → colored dye.",materials:["Glucose reagent","Spectro","Serum"],procedure:["Mix","Incubate 10min","Read 500nm"],result:"Absorbance",normal:"Fasting:70-100mg/dL",safety:["Reagent caution"],tips:"Fasting sample best."},
      {id:"urea",title:"Blood Urea",intro:"End product of protein metabolism. Kidney function test.",aim:"To measure urea.",principles:"Urease converts urea to ammonia.",materials:["Urea kit","Serum"],procedure:["Mix reagent","Incubate","Read"],result:"mg/dL",normal:"15-40",safety:["PPE"],tips:"High in renal failure."},
      {id:"creatinine",title:"Serum Creatinine",intro:"Muscle metabolism product. GFR marker.",aim:"To measure creatinine.",principles:"Jaffe reaction with alkaline picrate.",materials:["Creatinine kit","Serum"],procedure:["Mix","Wait","Read 520nm"],result:"mg/dL",normal:"0.6-1.2",safety:["Gloves"],tips:"More specific than urea."},
      {id:"alt",title:"Alanine Aminotransferase",intro:"Liver enzyme. Raised in hepatitis.",aim:"To measure ALT.",principles:"ALT catalyzes transfer of amino group.",materials:["ALT kit","Serum","Spectro"],procedure:["Mix","Incubate","Read 340nm"],result:"IU/L",normal:"<40",safety:["PPE"],tips:"More liver specific than AST."},
      {id:"ast",title:"Aspartate Aminotransferase",intro:"Liver and cardiac enzyme.",aim:"To measure AST.",principles:"Similar to ALT.",materials:["AST kit","Serum"],procedure:["Mix","Incubate","Read"],result:"IU/L",normal:"<40",safety:["Gloves"],tips:"Also raised in MI."},
      {id:"bilirubin",title:"Total & Direct Bilirubin",intro:"Hemoglobin breakdown product.",aim:"To measure bilirubin.",principles:"Diazotization with sulfanilic acid.",materials:["Bilirubin kit","Serum"],procedure:["Add reagent","Incubate","Read"],result:"mg/dL",normal:"Total:<1.2 Direct:<0.3",safety:["Light sensitive"],tips:"High = jaundice."},
      {id:"cholesterol",title:"Serum Cholesterol",intro:"Lipid profile component.",aim:"To measure cholesterol.",principles:"Cholesterol esterase → H2O2 → dye.",materials:["Cholesterol kit","Serum"],procedure:["Mix","Incubate","Read"],result:"mg/dL",normal:"<200",safety:["PPE"],tips:"Fasting sample."},
      {id:"protein",title:"Total Protein",intro:"Albumin + Globulin.",aim:"To measure total protein.",principles:"Biuret reaction → violet complex.",materials:["Biuret reagent","Serum"],procedure:["Mix","Incubate","Read 540nm"],result:"g/dL",normal:"6-8",safety:["Caustic reagent"],tips:"Low in malnutrition."},
      {id:"electrolytes",title:"Serum Electrolytes",intro:"Na, K, Cl, HCO3.",aim:"To measure electrolytes.",principles:"Ion selective electrode.",materials:["ISE machine","Serum"],procedure:["Load sample","Run"],result:"mmol/L",normal:"Na:135-145 K:3.5-5.0",safety:["Machine safety"],tips:"Critical for fluid balance."},
      {id:"amylase",title:"Serum Amylase",intro:"Pancreatic enzyme.",aim:"To measure amylase.",principles:"Hydrolysis of starch substrate.",materials:["Amylase kit","Serum"],procedure:["Mix","Incubate","Read"],result:"IU/L",normal:"30-110",safety:["Gloves"],tips:"High in pancreatitis."}
    ]},
    {id:"microbiology",name:"Medical Microbiology",analyses:[
      {id:"gs",title:"Gram Stain",intro:"Differentiates bacteria into Gram + and -.",aim:"To stain bacteria.",principles:"Crystal violet-iodine complex retained by thick peptidoglycan.",materials:["Slide","Crystal violet","Iodine","Alcohol","Safranin"],procedure:["Make smear","Heat fix","CV 1min","Iodine 1min","Alcohol decolorize","Safranin 30s"],result:"Purple=Gram+ Pink=Gram-",normal:"N/A",safety:["Biosafety"],tips:"Do not over-decolorize."},
      {id:"zn",title:"Ziehl-Neelsen Stain",intro:"Detects acid-fast bacilli like TB.",aim:"To demonstrate AFB.",principles:"Carbol fuchsin penetrates waxy cell wall.",materials:["Slide","Carbol fuchsin","Acid alcohol","Methylene blue"],procedure:["Smear","Heat stain","Acid wash","Counterstain"],result:"Red=AFB Blue=other",normal:"Negative",safety:["BSL2"],tips:"Heat is key for penetration."},
      {id:"culture",title:"Urine Culture",intro:"Detects UTI pathogens.",aim:"To isolate bacteria from urine.",principles:"Quantitative culture on CLED.",materials:["CLED plate","Loop","Incubator"],procedure:["Inoculate 1μL","Incubate 24h","Count colonies"],result:"CFU/mL",normal:"<10000",safety:["BSL2"],tips:">100000 = significant."},
      {id:"msu",title:"Midstream Urine Collection",intro:"Clean catch to avoid contamination.",aim:"To collect urine aseptically.",principles:"Clean urethral opening before collection.",materials:["Sterile container","Wipes"],procedure:["Clean genitals","Start void","Collect midstream"],result:"Clean sample",normal:"N/A",safety:["Patient education"],tips:"First morning sample best."},
      {id:"bloodculture",title:"Blood Culture",intro:"Detects bacteremia.",aim:"To isolate organisms from blood.",principles:"Blood inoculated into broth.",materials:["Blood culture bottle","Syringe"],procedure:["Aseptic draw","Inoculate","Incubate 7days"],result:"Growth/No growth",normal:"No growth",safety:["Strict asepsis"],tips:"2 sets from different sites."},
      {id:"sputum",title:"Sputum Culture",intro:"Respiratory pathogens.",aim:"To isolate respiratory bacteria.",principles:"Culture on blood and chocolate agar.",materials:["Sputum container","Agar plates"],procedure:["Collect sputum","Inoculate","Incubate"],result:"Organism ID",normal:"Normal flora",safety:["TB precautions"],tips:"Reject saliva."},
      {id:"wound",title:"Wound Swab Culture",intro:"Identifies wound pathogens.",aim:"To isolate bacteria.",principles:"Swab inoculated on media.",materials:["Swab","Media"],procedure:["Swab wound","Plate","Incubate"],result:"Organism + sensitivity",normal:"No pathogen",safety:["PPE"],tips:"Take from depth."},
      {id:"stool",title:"Stool Culture",intro:"Enteric pathogens.",aim:"To isolate Salmonella, Shigella.",principles:"Selective media: XLD, SS.",materials:["Stool container","Media"],procedure:["Inoculate","Incubate","Identify"],result:"Pathogen ID",normal:"Normal flora",safety:["BSL2"],tips:"Fresh sample."},
      {id:"csf",title:"CSF Analysis",intro:"Meningitis diagnosis.",aim:"To analyze CSF.",principles:"Cell count, chemistry, culture.",materials:["CSF tube","Chamber"],procedure:["Cell count","Glucose","Protein","Culture"],result:"Cells, protein, glucose",normal:"<5 cells, Glucose 50-80",safety:["BSL2"],tips:"Urgent processing."},
      {id:"sensitivity",title:"Antibiotic Sensitivity",intro:"Determines drug effectiveness.",aim:"To test antibiotic susceptibility.",principles:"Kirby-Bauer disk diffusion.",materials:["Mueller-Hinton agar","Antibiotic disks"],procedure:["Inoculate","Add disks","Incubate","Measure zones"],result:"S, I, R",normal:"N/A",safety:["BSL2"],tips:"Use standard inoculum."}
    ]},
