const LAB_DATA = {
  settings:{
    freeLimit:5,
    premiumPrice:2200,
    premiumDurationDays:60, // renews every 2 months
    paystackPublicKey:"pk_test_c7e019ceeeed3e83bcdd2d0e55bf6419ec18e9ad", // replace with your LIVE public key (pk_live_...) — never put the secret key (sk_...) in this file
    paystackPlanCode:"PLN_bbrr3qjnhkh7onb", // create a recurring Plan in the Paystack dashboard (Payments > Plans), ₦2,200 every 60 days
  
  },
  perks:[
    "🔓 Unlimited analyses — no daily read limit",
    "🧮 Full unit converter for lab values",
    "📊 Personal progress dashboard by unit",
    "🔔 Study reminders & new-content alerts",
    "📴 Full offline access, synced across your devices",
    "🆕 All future units and analyses as they're added"
  ],
  units:[
    {id:"hematology",name:"Hematology",analyses:[
      {id:"pcv",title:"Packed Cell Volume (PCV)",intro:"PCV measures the volume of red blood cells expressed as a percentage of total blood volume. It is used to assess anemia, polycythemia and dehydration.",aim:"To determine the percentage of red blood cells in whole blood.",principles:"Anticoagulated blood is centrifuged at high speed. Red cells pack at the bottom. The ratio of packed cells to total blood gives PCV.",materials:["EDTA blood sample","Microhematocrit tubes","Clay sealant","Microhematocrit centrifuge","Reader"],procedure:["Mix blood well","Fill tube 3/4 and seal end","Centrifuge at 10,000rpm for 5min","Read PCV with reader"],result:"Red cell column as % of total column",normal:"Male: 40-54%. Female: 37-47%",safety:["Wear PPE","Dispose sharps","Decontaminate area"],tips:"Rule of 3: Hb x 3 ≈ PCV. Low PCV = anemia. High PCV = dehydration."},
      {id:"hb",title:"Hemoglobin Estimation - Sahli Method",intro:"Hemoglobin carries oxygen. Sahli method converts Hb to acid hematin and color is matched.",aim:"To estimate hemoglobin concentration.",principles:"Hb + HCl → Acid hematin. Color intensity compared to standard.",materials:["Sahli apparatus","N/10 HCl","Hb pipette","Distilled water"],procedure:["Put HCl to 20 mark","Add 20μL blood","Wait 10min","Add water till color match","Read g/dL"],result:"g/dL directly from tube",normal:"Male:13.5-17.5 Female:12-15.5",safety:["Handle HCl carefully"],tips:"Wait full 10min. Rushing gives low result."},
      {id:"esr",title:"Erythrocyte Sedimentation Rate",intro:"ESR measures rate RBCs settle in 1hr. Increased in inflammation.",aim:"To measure ESR.",principles:"Inflammatory proteins cause RBC aggregation and faster settling.",materials:["Westergren tube","ESR stand","Sodium citrate blood"],procedure:["Dilute blood 4:1 with citrate","Fill to 200mm","Stand 1hr","Read mm"],result:"mm/hr",normal:"M:<15 F:<20",safety:["Universal precautions"],tips:"Non-specific test. Used to monitor disease activity."},
      {id:"twbc",title:"Total White Blood Cell Count",intro:"Counts all WBCs. Elevated in infection, leukemia.",aim:"To determine WBC count per μL.",principles:"Blood diluted 1:20, WBCs counted in Neubauer chamber.",materials:["WBC pipette","Turks fluid","Counting chamber"],procedure:["Dilute blood","Load chamber","Count 4 squares","Calculate x50"],result:"Cells/μL",normal:"4000-11000",safety:["Wear gloves"],tips:"Turks lyses RBCs and stains WBC nuclei."},
      {id:"platelet",title:"Platelet Count",intro:"Platelets aid clotting. Low causes bleeding.",aim:"To count platelets.",principles:"Blood diluted 1:100, counted in chamber.",materials:["Platelet pipette","Rees-Ecker fluid","Chamber"],procedure:["Dilute","Load","Count 5 squares","x1000"],result:"/μL",normal:"150000-450000",safety:["Avoid aerosols"],tips:"Clumping causes false low."},
      {id:"diff",title:"Differential WBC Count",intro:"Percentage of each WBC type.",aim:"To identify WBC types.",principles:"Stained film examined, 100 cells counted.",materials:["Slides","Leishman stain","Oil immersion"],procedure:["Make film","Stain","Count 100 WBCs"],result:"% Neut, Lymph, Mono, Eos, Baso",normal:"N:40-75 L:20-45",safety:["Handle slides"],tips:"Good film = good diff."},
      {id:"film",title:"Peripheral Blood Film",intro:"Assesses RBC, WBC, Platelet morphology.",aim:"To prepare quality blood film.",principles:"Thin spread of blood for microscopy.",materials:["2 slides","Blood","Stain"],procedure:["Drop blood","Spread at 45°","Air dry","Stain"],result:"Thin film with feather edge",normal:"N/A",safety:["No mouth pipetting"],tips:"Feather edge must be smooth."},
      {id:"retic",title:"Reticulocyte Count",intro:"Young RBCs. Shows marrow activity.",aim:"To count retics.",principles:"New methylene blue stains RNA reticulum.",materials:["New methylene blue","Tube","Slides"],procedure:["Mix 1:1","Incubate 15min","Make film","Count 1000 RBCs"],result:"%",normal:"0.5-2.5%",safety:["Dye stains"],tips:"High in hemolytic anemia."},
      {id:"bt",title:"Bleeding Time",intro:"Tests platelet and capillary function.",aim:"To measure bleeding time.",principles:"Standard incision, time to stop.",materials:["Lancet","Filter paper","Timer"],procedure:["Clean ear","3mm incision","Blot 30s","Stop when dry"],result:"Minutes",normal:"2-9min",safety:["Sharps disposal"],tips:"Prolonged in thrombocytopenia."},
      {id:"ct",title:"Clotting Time",intro:"Intrinsic pathway function.",aim:"To measure clotting time.",principles:"Blood in glass tube clots.",materials:["Glass tube","37°C bath","Lancet"],procedure:["Collect blood","Place in bath","Tilt 30s","Note clot"],result:"Minutes",normal:"5-10min",safety:["Blood handling"],tips:"Prolonged in hemophilia."}
    ]},
    {id:"chemistry",name:"Clinical Chemistry",analyses:[
      {id:"glucose",title:"Blood Glucose",intro:"Measures blood sugar. Key in diabetes.",aim:"To estimate glucose.",principles:"Glucose oxidase → H2O2 → colored dye.",materials:["Glucose reagent","Spectro","Serum"],procedure:["Mix","Incubate 10min","Read 500nm"],result:"Absorbance",normal:"Fasting:70-100mg/dL",safety:["Reagent caution"],tips:"Fasting sample best."},
      {id:"urea",title:"Blood Urea",intro:"End product of protein metabolism. Kidney function test.",aim:"To measure urea.",principles:"Urease converts urea to ammonia.",materials:["Urea kit","Serum"],procedure:["Mix reagent","Incubate","Read"],result:"mg/dL",normal:"15-40",safety:["PPE"],tips:"High in renal failure."},
      {id:"creatinine",title:"Serum Creatinine",intro:"Muscle metabolism product. GFR marker.",aim:"To measure creatinine.",principles:"Jaffe reaction with alkaline picrate.",materials:["Creatinine kit","Serum"],procedure:["Mix","Wait","Read 520nm"],result:"mg/dL",normal:"0.6-1.2",safety:["Gloves"],tips:"More specific than urea."},
      {id:"alt",title:"Alanine Aminotransferase",intro:"Liver enzyme. Raised in hepatitis.",aim:"To measure ALT.",principles:"ALT catalyzes transfer of amino group.",materials:["ALT kit","Serum","Spectro"],procedure:["Mix","Incubate","Read 340nm"],result:"IU/L",normal:"<40",safety:["PPE"],tips:"More liver specific than AST."},
      {id:"ast",title:"Aspartate Aminotransferase",intro:"Liver and cardiac enzyme.",aim:"To measure AST.",principles:"Similar to ALT.",materials:["AST kit","Serum"],procedure:["Mix","Incubate","Read"],result:"IU/L",normal:"<40",safety:["Gloves"],tips:"Also raised in MI."},
      {id:"bilirubin",title:"Total & Direct Bilirubin",intro:"Hemoglobin breakdown product.",aim:"To measure bilirubin.",principles:"Diazotization with sulfanilic acid.",materials:["Bilirubin kit","Serum"],procedure:["Add reagent","Incubate","Read"],result:"mg/dL",normal:"Total:<1.2 Direct:<0.3",safety:["Light sensitive"],tips:"High = jaundice."},
      {id:"cholesterol",title:"Serum Cholesterol",intro:"Lipid profile component.",aim:"To measure cholesterol.",principles:"Cholesterol esterase → H2O2 → dye.",materials:["Cholesterol kit","Serum"],procedure:["Mix","Incubate","Read"],result:"mg/dL",normal:"<200",safety:["PPE"],tips:"Fasting sample."},
      {id:"protein",title:"Total Protein",intro:"Albumin + Globulin.",aim:"To measure total protein.",principles:"Biuret reaction → violet complex.",materials:["Biuret reagent","Serum"],procedure:["Mix","Incubate","Read 540nm"],result:"g/dL",normal:"6-8",safety:["Caustic reagent"],tips:"Low in malnutrition."},
      {id:"electrolytes",title:"Serum Electrolytes",intro:"Na, K, Cl, HCO3.",aim:"To measure electrolytes.",principles:"Ion selective electrode.",materials:["ISE machine","Serum"],procedure:["Load sample","Run"],result:"mmol/L",normal:"Na:135-145 K:3.5-5.0",safety:["Machine safety"],tips:"Critical for fluid balance."},
      {id:"amylase",title:"Serum Amylase",intro:"Pancreatic enzyme.",aim:"To measure amylase.",principles:"Hydrolysis of starch substrate.",materials:["Amylase kit","Serum"],procedure:["Mix","Incubate","Read"],result:"IU/L",normal:"30-110",safety:["Gloves"],tips:"High in pancreatitis."}
    ]},
    {id:"microbiology",name:"Medical Microbiology",analyses:[
      {id:"gs",title:"Gram Stain",intro:"Differentiates bacteria into Gram + and -.",aim:"To stain bacteria.",principles:"Crystal violet-iodine complex retained by thick peptidoglycan.",materials:["Slide","Crystal violet","Iodine","Alcohol","Safranin"],procedure:["Make smear","Heat fix","CV 1min","Iodine 1min","Alcohol decolorize","Safranin 30s"],result:"Purple=Gram+ Pink=Gram-",normal:"N/A",safety:["Biosafety"],tips:"Do not over-decolorize."},
      {id:"zn",title:"Ziehl-Neelsen Stain",intro:"Detects acid-fast bacilli like TB.",aim:"To demonstrate AFB.",principles:"Carbol fuchsin penetrates waxy cell wall.",materials:["Slide","Carbol fuchsin","Acid alcohol","Methylene blue"],procedure:["Smear","Heat stain","Acid wash","Counterstain"],result:"Red=AFB Blue=other",normal:"Negative",safety:["BSL2"],tips:"Heat is key for penetration."},
      {id:"culture",title:"Urine Culture",intro:"Detects UTI pathogens.",aim:"To isolate bacteria from urine.",principles:"Quantitative culture on CLED.",materials:["CLED plate","Loop","Incubator"],procedure:["Inoculate 1μL","Incubate 24h","Count colonies"],result:"CFU/mL",normal:"<10000",safety:["BSL2"],tips:">100000 = significant."},
      {id:"msu",title:"Midstream Urine Collection",intro:"Clean catch to avoid contamination.",aim:"To collect urine aseptically.",principles:"Clean urethral opening before collection.",materials:["Sterile container","Wipes"],procedure:["Clean genitals","Start void","Collect midstream"],result:"Clean sample",normal:"N/A",safety:["Patient education"],tips:"First morning sample best."},
      {id:"bloodculture",title:"Blood Culture",intro:"Detects bacteremia.",aim:"To isolate organisms from blood.",principles:"Blood inoculated into broth.",materials:["Blood culture bottle","Syringe"],procedure:["Aseptic draw","Inoculate","Incubate 7days"],result:"Growth/No growth",normal:"No growth",safety:["Strict asepsis"],tips:"2 sets from different sites."},
      {id:"sputum",title:"Sputum Culture",intro:"Respiratory pathogens.",aim:"To isolate respiratory bacteria.",principles:"Culture on blood and chocolate agar.",materials:["Sputum container","Agar plates"],procedure:["Collect sputum","Inoculate","Incubate"],result:"Organism ID",normal:"Normal flora",safety:["TB precautions"],tips:"Reject saliva."},
      {id:"wound",title:"Wound Swab Culture",intro:"Identifies wound pathogens.",aim:"To isolate bacteria.",principles:"Swab inoculated on media.",materials:["Swab","Media"],procedure:["Swab wound","Plate","Incubate"],result:"Organism + sensitivity",normal:"No pathogen",safety:["PPE"],tips:"Take from depth."},
      {id:"stool",title:"Stool Culture",intro:"Enteric pathogens.",aim:"To isolate Salmonella, Shigella.",principles:"Selective media: XLD, SS.",materials:["Stool container","Media"],procedure:["Inoculate","Incubate","Identify"],result:"Pathogen ID",normal:"Normal flora",safety:["BSL2"],tips:"Fresh sample."},
      {id:"csf",title:"CSF Analysis",intro:"Meningitis diagnosis.",aim:"To analyze CSF.",principles:"Cell count, chemistry, culture.",materials:["CSF tube","Chamber"],procedure:["Cell count","Glucose","Protein","Culture"],result:"Cells, protein, glucose",normal:"<5 cells, Glucose 50-80",safety:["BSL2"],tips:"Urgent processing."},
      {id:"sensitivity",title:"Antibiotic Sensitivity",intro:"Determines drug effectiveness.",aim:"To test antibiotic susceptibility.",principles:"Kirby-Bauer disk diffusion.",materials:["Mueller-Hinton agar","Antibiotic disks"],procedure:["Inoculate","Add disks","Incubate","Measure zones"],result:"S, I, R",normal:"N/A",safety:["BSL2"],tips:"Use standard inoculum."}
    ]},
       {id:"immunology",name:"Immunology",analyses:[
  {id:"hiv",title:"HIV Rapid Test",intro:"The HIV rapid test detects antibodies to HIV-1 and HIV-2 in blood. It is used for screening and early detection of HIV infection.",aim:"To qualitatively detect HIV antibodies in human serum or plasma.",principles:"It is a lateral flow chromatographic immunoassay. If HIV antibodies are present, they bind to antigen-coated colloidal gold and form a visible line.",materials:["HIV rapid test kit","Lancing device","Capillary tube","Buffer","Timer"],procedure:["Perform hand hygiene and wear gloves","Collect finger-prick blood","Add 1 drop of blood to sample well","Add 2 drops of buffer","Read result at 15 minutes"],result:"1 line = Negative. 2 lines = Reactive. No control line = Invalid",normal:"Non-reactive",safety:["Universal precautions","Dispose sharps in safety box","Decontaminate surface"],tips:"Always confirm reactive results with ELISA and Western Blot. Window period is 3 months."},
  
  {id:"hbsag",title:"Hepatitis B Surface Antigen Test",intro:"HBsAg test detects the surface antigen of Hepatitis B virus. It indicates current HBV infection.",aim:"To detect HBsAg in serum or plasma.",principles:"Sandwich ELISA or immunochromatography. HBsAg binds to anti-HBs antibodies on the test strip.",materials:["HBsAg test kit","Serum sample","Pipette","Timer"],procedure:["Add 50μL of serum to sample well","Add buffer","Incubate 15 minutes","Read result"],result:"1 line = Negative. 2 lines = Positive",normal:"Negative",safety:["Handle blood as infectious","Use PPE"],tips:"Vaccinated persons may be HBsAb positive but HBsAg negative."},

  {id:"widal",title:"Widal Test",intro:"Widal test detects agglutinating antibodies against Salmonella typhi and paratyphi in typhoid fever.",aim:"To detect anti-O and anti-H antibodies against Salmonella.",principles:"Patient serum is mixed with antigen suspensions. Agglutination indicates presence of antibodies.",materials:["Widal antigen kit","Serum","Test tubes","Water bath"],procedure:["Make serial dilutions of serum 1:20 to 1:640","Add antigen","Incubate at 37°C for 18-24hrs","Observe agglutination"],result:"Titer ≥1:160 considered significant",normal:"<1:80",safety:["Handle serum carefully"],tips:"Single high titer is not diagnostic. 4-fold rise in paired sera is better."},

  {id:"ra",title:"Rheumatoid Factor Test",intro:"RF is an autoantibody against IgG. It is present in Rheumatoid Arthritis.",aim:"To detect Rheumatoid Factor in serum.",principles:"Latex particles coated with human IgG agglutinate in presence of RF.",materials:["RF latex kit","Serum","Slide","Mixer"],procedure:["Place 1 drop serum and 1 drop reagent on slide","Mix and rotate 2 minutes","Observe agglutination"],result:"Agglutination = Positive",normal:"<20 IU/mL",safety:["Wear gloves"],tips:"RF can be positive in other autoimmune diseases and infections."},

  {id:"crp",title:"C-Reactive Protein",intro:"CRP is an acute phase protein that rises rapidly in inflammation and infection.",aim:"To measure CRP levels in serum.",principles:"Latex agglutination. CRP binds to anti-CRP antibodies on latex particles.",materials:["CRP kit","Serum","Slide"],procedure:["Mix serum and reagent","Rotate 2 minutes","Observe agglutination"],result:"Positive if agglutination. Quantitate by dilution",normal:"<10 mg/L",safety:["Universal precautions"],tips:"Rises within 6 hours of inflammation. Falls quickly with treatment."},

  {id:"asot",title:"Anti-Streptolysin O Titer",intro:"ASOT detects antibodies against Streptolysin O produced by Group A Streptococcus.",aim:"To detect ASOT in serum.",principles:"Latex particles coated with streptolysin O agglutinate with anti-streptolysin antibodies.",materials:["ASOT kit","Serum","Slide"],procedure:["Mix serum and latex reagent","Rotate 2 minutes","Read agglutination"],result:"Titer in IU/mL",normal:"<200 IU/mL",safety:["Wear PPE"],tips:"Elevated 1-3 weeks after strep infection. Used in rheumatic fever diagnosis."},

  {id:"malaria_rdt",title:"Malaria Rapid Diagnostic Test",intro:"RDT detects Plasmodium antigens HRP2 and pLDH in blood.",aim:"To diagnose malaria infection.",principles:"Immunochromatographic test. Parasite antigen binds to antibodies on test strip.",materials:["Malaria RDT kit","Blood","Buffer","Lancet"],procedure:["Collect blood","Add to sample pad","Add buffer","Read at 15 minutes"],result:"HRP2 line = P.falciparum. pLDH line = other species",normal:"Negative",safety:["Sharps disposal"],tips:"Always confirm with blood film. HRP2 can persist after treatment."},

  {id:"pregnancy",title:"Urine Pregnancy Test",intro:"Detects human chorionic gonadotropin hormone in urine.",aim:"To confirm pregnancy.",principles:"Anti-hCG antibodies bind to hCG in urine producing colored line.",materials:["Pregnancy strip","Urine container"],procedure:["Collect early morning urine","Dip strip for 10 seconds","Read at 5 minutes"],result:"2 lines = Positive",normal:"Negative",safety:["Hygiene"],tips:"Most sensitive in first morning urine."},

  {id:"vdrl",title:"VDRL Test",intro:"VDRL screens for syphilis by detecting reagin antibodies.",aim:"To screen for syphilis.",principles:"Cardiolipin antigen reacts with antibodies forming flocculation.",materials:["VDRL antigen","Serum","Rotator","Slide"],procedure:["Heat inactivate serum","Add antigen","Rotate 4 minutes","Examine microscopically"],result:"Reactive or Non-reactive",normal:"Non-reactive",safety:["Blood precautions"],tips:"Biological false positives occur. Confirm with TPHA."},

  {id:"coombs",title:"Direct Coombs Test",intro:"Detects antibodies or complement attached to RBC surface.",aim:"To detect in-vivo sensitization of RBCs.",principles:"Anti-human globulin binds to IgG or complement on RBCs causing agglutination.",materials:["Coombs serum","Patient RBCs","Test tube","Centrifuge"],procedure:["Wash RBCs 3 times","Add Coombs reagent","Centrifuge","Look for agglutination"],result:"Agglutination = Positive",normal:"Negative",safety:["Blood safety"],tips:"Used in hemolytic disease of newborn and autoimmune hemolytic anemia."}
]},
{id:"histopathology",name:"Histopathology",analyses:[
  {id:"fixation",title:"Tissue Fixation",intro:"Fixation preserves tissue structure and prevents autolysis and putrefaction.",aim:"To preserve tissue in near life-like state.",principles:"10% Formalin cross-links proteins and inactivates enzymes.",materials:["10% Buffered formalin","Specimen container","Tissue"],procedure:["Place tissue immediately in formalin","Tissue to fixative ratio 1:10","Fix for 24-48 hours"],result:"Firm, preserved tissue",normal:"N/A",safety:["Use fume hood","Wear gloves"],tips:"Do not overfix. It can interfere with IHC."},

  {id:"processing",title:"Tissue Processing",intro:"Processing removes water and infiltrates tissue with paraffin.",aim:"To make tissue suitable for sectioning.",principles:"Dehydration with alcohol, clearing with xylene, infiltration with paraffin.",materials:["Tissue processor","Alcohol grades","Xylene","Paraffin"],procedure:["Dehydrate 70% to 100% alcohol","Clear in xylene","Infiltrate in paraffin","Embed"],result:"Paraffin block",normal:"N/A",safety:["Xylene is toxic"],tips:"Standard cycle is 12-16 hours."},

  {id:"microtomy",title:"Microtomy and Sectioning",intro:"Cutting thin sections from paraffin block for microscopy.",aim:"To obtain 4-5μm sections.",principles:"Paraffin block is cut using a microtome.",materials:["Microtome","Paraffin block","Water bath","Slides"],procedure:["Trim block","Cut ribbon of sections","Float on 45°C water bath","Mount on slide"],result:"Thin tissue ribbon",normal:"N/A",safety:["Sharp blades"],tips:"Water bath temperature is critical to avoid wrinkles."},

  {id:"he",title:"Hematoxylin and Eosin Staining",intro:"H&E is the routine stain in histopathology.",aim:"To stain nuclei and cytoplasm for diagnosis.",principles:"Hematoxylin stains nuclei blue. Eosin stains cytoplasm pink.",materials:["H&E reagents","Staining jars","Slides"],procedure:["Deparaffinize","Hematoxylin 5min","Acid alcohol dip","Eosin 1min","Dehydrate and mount"],result:"Blue nuclei, Pink cytoplasm",normal:"N/A",safety:["Reagent handling"],tips:"Good differentiation is key to nuclear detail."},

  {id:"fnac",title:"Fine Needle Aspiration Cytology",intro:"FNAC obtains cells from a lesion for diagnosis.",aim:"To prepare cytological smears.",principles:"Cells are aspirated and smeared on slide then stained.",materials:["Needle","Syringe","Slides","Stains"],procedure:["Aspirate lesion","Express material on slide","Smear","Fix and stain"],result:"Cellular smear",normal:"N/A",safety:["Sharps injury risk"],tips:"Air dry for MGG stain. Wet fix for Pap."},

  {id:"ihc",title:"Immunohistochemistry",intro:"IHC detects specific antigens in tissue using antibodies.",aim:"To identify cell markers and proteins.",principles:"Primary antibody binds antigen. Secondary antibody with enzyme produces color.",materials:["Primary antibody","Secondary antibody","DAB","Microscope"],procedure:["Deparaffinize","Antigen retrieval","Block","Primary Ab","Secondary","DAB","Counterstain"],result:"Brown positive staining",normal:"N/A",safety:["DAB is carcinogenic"],tips:"Always run positive and negative controls."},

  {id:"frozen",title:"Frozen Section",intro:"Rapid intraoperative diagnosis.",aim:"To provide diagnosis within 15 minutes.",principles:"Tissue is rapidly frozen and sectioned in cryostat.",materials:["Cryostat","OCT","Tissue"],procedure:["Freeze tissue","Cut 5μm section","Rapid H&E stain"],result:"Quick diagnosis",normal:"N/A",safety:["Cold burns"],tips:"Artifact is common. Not for permanent diagnosis."},

  {id:"special",title:"Special Stains - PAS",intro:"PAS stains carbohydrates and mucins.",aim:"To demonstrate glycogen and mucin.",principles:"Periodic acid oxidizes glycol to aldehyde which reacts with Schiff reagent.",materials:["PAS kit","Slides"],procedure:["Deparaffinize","Periodic acid","Schiff reagent","Counterstain"],result:"Magenta positive",normal:"N/A",safety:["Reagents"],tips:"Used for fungi and basement membrane."},

  {id:"biopsy",title:"Biopsy Handling",intro:"Proper handling of biopsy is crucial for diagnosis.",aim:"To process small tissue samples.",principles:"Same as routine but with gentle handling.",materials:["Formalin","Cassettes"],procedure:["Immediate fixation","Label properly","Process carefully"],result:"Processable tissue",normal:"N/A",safety:["Gloves"],tips:"Do not squeeze tissue with forceps."},

  {id:"reporting",title:"Histopathology Reporting",intro:"Final diagnosis based on microscopic findings.",aim:"To provide clinicopathological diagnosis.",principles:"Correlation of gross and microscopic features.",materials:["Microscope","Report form"],procedure:["Scan slide","Describe findings","Give diagnosis","Comment"],result:"Pathology report",normal:"N/A",safety:["N/A"],tips:"Correlation with clinical data improves accuracy."}
]},
{id:"bloodbank",name:"Blood Transfusion Science",analyses:[
  {id:"abo",title:"ABO Blood Grouping",intro:"ABO system classifies blood based on A and B antigens on RBCs.",aim:"To determine ABO blood group.",principles:"Antigen-antibody reaction. Cell grouping and serum grouping.",materials:["Anti-A","Anti-B","Anti-AB","Patient cells","Patient serum"],procedure:["Cell grouping: Mix cells with antisera","Serum grouping: Mix serum with A and B cells","Observe agglutination"],result:"Group A, B, AB, or O",normal:"N/A",safety:["Blood precautions"],tips:"Cell and serum grouping must agree."},

  {id:"rh",title:"Rh D Typing",intro:"Detects presence of D antigen on RBCs.",aim:"To determine Rh status.",principles:"Anti-D antibodies cause agglutination if D antigen present.",materials:["Anti-D reagent","Patient cells","Test tube"],procedure:["Add cells and Anti-D","Incubate 37°C","Centrifuge","Read"],result:"Rh Positive or Negative",normal:"N/A",safety:["Gloves"],tips:"Do weak D testing for negatives."},

  {id:"crossmatch",title:"Crossmatching",intro:"Tests compatibility between donor blood and recipient.",aim:"To prevent transfusion reaction.",principles:"Donor RBCs tested against recipient serum.",materials:["Donor cells","Recipient serum","Test tube"],procedure:["Major crossmatch","Incubate 37°C","Add Coombs","Check agglutination"],result:"Compatible or Incompatible",normal:"Compatible",safety:["BSL2"],tips:"Most important step before transfusion."},

  {id:"antibody_screen",title:"Antibody Screening",intro:"Detects irregular antibodies in recipient serum.",aim:"To screen for unexpected antibodies.",principles:"Patient serum tested against panel of known antigen cells.",materials:["Panel cells","Patient serum","Test tubes"],procedure:["Incubate serum with panel cells","Wash","Add Coombs","Read"],result:"Positive or Negative",normal:"Negative",safety:["Gloves"],tips:"3 cell panel is standard."},

  {id:"dat",title:"Direct Antiglobulin Test",intro:"Detects antibodies bound to patient RBCs.",aim:"To diagnose immune hemolytic anemia.",principles:"Coombs reagent binds to IgG or complement on RBCs.",materials:["Coombs serum","Patient RBCs"],procedure:["Wash RBCs","Add Coombs","Centrifuge","Read"],result:"Positive or Negative",normal:"Negative",safety:["Blood safety"],tips:"Positive in HDN and AIHA."},

  {id:"titer",title:"Antibody Titer",intro:"Measures strength of antibody.",aim:"To quantify antibody levels.",principles:"Serial dilution of serum tested against antigen.",materials:["Serum","Antigen cells","Test tubes"],procedure:["Make doubling dilutions","Test each","Record last positive"],result:"Titer value",normal:"N/A",safety:["PPE"],tips:"Used to monitor HDN."},

  {id:"elution",title:"Elution Technique",intro:"Removes antibody from RBC surface.",aim:"To identify antibody specificity.",principles:"Heat or chemical treatment releases antibody.",materials:["Elution kit","Sensitized RBCs"],procedure:["Heat RBCs","Centrifuge","Test eluate"],result:"Antibody identified",normal:"N/A",safety:["Heat hazard"],tips:"Used in autoantibody cases."},

  {id:"storage",title:"Blood Component Storage",intro:"Proper storage maintains blood viability.",aim:"To store blood safely.",principles:"Different components stored at different temperatures.",materials:["Blood fridge","Freezer"],procedure:["Whole blood: 2-6°C","Platelets: 22°C","FFP: -18°C"],result:"Viable blood",normal:"42 days for PRBC",safety:["Temperature monitoring"],tips:"Check fridge temperature twice daily."},

  {id:"reaction",title:"Investigation of Transfusion Reaction",intro:"Investigates suspected transfusion reaction.",aim:"To determine cause of reaction.",principles:"Repeat grouping, crossmatch, and DAT.",materials:["Post-transfusion sample","Blood bag"],procedure:["Stop transfusion","Send samples","Repeat tests","Check plasma for hemolysis"],result:"Reaction type",normal:"None",safety:["Urgent"],tips:"Most reactions are due to clerical error."},

  {id:"donor_screen",title:"Donor Blood Screening",intro:"Screens donor blood for TTIs.",aim:"To ensure safe blood.",principles:"Test for HIV, HBV, HCV, Syphilis.",materials:["Donor blood","Test kits"],procedure:["Collect sample","Test for 4 markers","Label unit"],result:"Reactive or Non-reactive",normal:"Non-reactive",safety:["BSL2"],tips:"Window period risk still exists."}
]},
  {id:"virology",name:"Virology",analyses:[
  {id:"hiv_elisa",title:"HIV ELISA Test",intro:"ELISA detects HIV antibodies or antigens in serum with high sensitivity.",aim:"To confirm HIV infection by detecting HIV antibodies.",principles:"Antigen-antibody reaction. Enzyme linked to antibody produces color with substrate.",materials:["ELISA kit","ELISA reader","Serum","Wash buffer"],procedure:["Add serum to antigen coated wells","Incubate 30min","Wash","Add conjugate","Add substrate","Read at 450nm"],result:"OD > Cut-off = Reactive",normal:"Non-reactive",safety:["BSL2","PPE"],tips:"Used as confirmatory test after rapid screening."},

  {id:"hbv_dna",title:"Hepatitis B Viral Load",intro:"HBV DNA quantifies Hepatitis B virus in blood.",aim:"To measure HBV viral load.",principles:"Real-time PCR amplifies HBV DNA and quantifies it.",materials:["PCR kit","RNA extractor","Serum","Thermal cycler"],procedure:["Extract DNA","Add to PCR mix","Run PCR 40 cycles","Analyze Ct value"],result:"IU/mL",normal:"Undetectable",safety:["BSL2","Avoid contamination"],tips:"Used to monitor treatment response."},

  {id:"hcv_antibody",title:"Hepatitis C Antibody Test",intro:"Detects antibodies to Hepatitis C virus.",aim:"To screen for HCV infection.",principles:"Immunoassay. HCV antigens bind to anti-HCV in serum.",materials:["HCV ELISA kit","Serum"],procedure:["Add serum to well","Incubate","Wash","Add conjugate","Read"],result:"Reactive or Non-reactive",normal:"Non-reactive",safety:["Blood precautions"],tips:"Reactive result needs PCR confirmation."},

  {id:"dengue",title:"Dengue NS1 Antigen Test",intro:"NS1 antigen appears in first week of dengue fever.",aim:"To detect acute dengue infection.",principles:"Immunochromatographic test for NS1 antigen.",materials:["Dengue RDT kit","Serum"],procedure:["Add serum to sample pad","Add buffer","Read in 15min"],result:"Line = Positive",normal:"Negative",safety:["PPE"],tips:"Best in first 7 days of fever."},

  {id:"rotavirus",title:"Rotavirus Antigen Test",intro:"Detects rotavirus in stool of children with diarrhea.",aim:"To diagnose rotavirus gastroenteritis.",principles:"Lateral flow immunoassay for rotavirus antigen.",materials:["Rotavirus kit","Stool"],procedure:["Mix stool with buffer","Add to test device","Read 10min"],result:"2 lines = Positive",normal:"Negative",safety:["BSL2"],tips:"Common in children <5 years."},

  {id:"covid_pcr",title:"SARS-CoV-2 PCR Test",intro:"PCR detects SARS-CoV-2 RNA.",aim:"To diagnose COVID-19.",principles:"RT-PCR amplifies viral RNA from nasopharyngeal swab.",materials:["VTM","Swab","RNA extraction kit","PCR kit"],procedure:["Collect NP swab","Extract RNA","RT-PCR","Analyze"],result:"Detected or Not detected",normal:"Not detected",safety:["BSL2","PPE"],tips:"Gold standard for COVID diagnosis."},

  {id:"influenza",title:"Influenza Rapid Test",intro:"Detects influenza A and B antigens.",aim:"To diagnose influenza.",principles:"Antigen detection in nasopharyngeal swab.",materials:["Flu kit","Swab"],procedure:["Collect swab","Add to device","Read 10min"],result:"A line or B line",normal:"Negative",safety:["PPE"],tips:"Most sensitive in first 48hrs of symptoms."},

  {id:"measles",title:"Measles IgM Test",intro:"IgM indicates recent measles infection.",aim:"To diagnose measles.",principles:"ELISA detects measles IgM antibodies.",materials:["Measles IgM kit","Serum"],procedure:["Add serum","Incubate","Wash","Read"],result:"Positive or Negative",normal:"Negative",safety:["Gloves"],tips:"Collect sample 3 days after rash."},

  {id:"herpes",title:"Herpes Simplex PCR",intro:"Detects HSV DNA in lesions or CSF.",aim:"To diagnose HSV infection.",principles:"PCR amplifies HSV DNA.",materials:["PCR kit","Swab or CSF"],procedure:["Extract DNA","Run PCR","Analyze"],result:"Detected or Not detected",normal:"Not detected",safety:["BSL2"],tips:"CSF PCR for HSV encephalitis."},

  {id:"yellow_fever",title:"Yellow Fever IgM",intro:"Detects recent yellow fever infection.",aim:"To confirm yellow fever.",principles:"ELISA for YF IgM antibodies.",materials:["YF IgM kit","Serum"],procedure:["Add serum","Incubate","Wash","Read"],result:"Positive or Negative",normal:"Negative",safety:["BSL2"],tips:"Cross-reacts with other flaviviruses."}
]},
{id:"cytology",name:"Cytology",analyses:[
  {id:"pap",title:"Pap Smear",intro:"Screens for cervical cancer and precancerous lesions.",aim:"To detect abnormal cervical cells.",principles:"Cells collected from cervix and stained with Pap stain.",materials:["Speculum","Ayre spatula","Slide","Fixative","Pap stain"],procedure:["Collect cells from cervix","Smear on slide","Fix immediately","Stain"],result:"NILM, LSIL, HSIL",normal:"Negative for intraepithelial lesion",safety:["Gloves"],tips:"Best taken mid-cycle. Avoid during menses."},

  {id:"fnac_breast",title:"FNAC Breast",intro:"Fine needle aspiration of breast lump.",aim:"To diagnose breast lesions cytologically.",principles:"Cells aspirated and examined microscopically.",materials:["Needle","Syringe","Slides","Stain"],procedure:["Aspirate lump","Make smear","Air dry/Fix","Stain"],result:"Benign, Suspicious, Malignant",normal:"N/A",safety:["Sharps safety"],tips:"Multiple passes increase yield."},

  {id:"sputum_cyto",title:"Sputum Cytology",intro:"Detects malignant cells in sputum.",aim:"To diagnose lung cancer.",principles:"Sputum cells stained and examined.",materials:["Sputum container","Slide","Stain"],procedure:["Collect early morning sputum","Make smear","Stain"],result:"Malignant cells or Negative",normal:"Negative",safety:["BSL2"],tips:"3 consecutive morning samples."},

  {id:"urine_cyto",title:"Urine Cytology",intro:"Detects bladder and urinary tract cancer cells.",aim:"To screen for urothelial carcinoma.",principles:"Centrifuged urine sediment examined.",materials:["Urine","Centrifuge","Slide","Stain"],procedure:["Centrifuge urine","Make smear","Stain"],result:"Malignant cells or Negative",normal:"Negative",safety:["PPE"],tips:"First morning urine best."},

  {id:"csf_cyto",title:"CSF Cytology",intro:"Detects malignant cells in CSF.",aim:"To diagnose CNS malignancy.",principles:"Centrifuged CSF examined for tumor cells.",materials:["CSF","Centrifuge","Slide"],procedure:["Centrifuge","Make smear","Stain"],result:"Malignant cells or Negative",normal:"No malignant cells",safety:["BSL2"],tips:"Process immediately."},

  {id:"pleural",title:"Pleural Fluid Cytology",intro:"Analyzes pleural effusion for malignancy.",aim:"To detect cancer cells in pleural fluid.",principles:"Fluid centrifuged and cells examined.",materials:["Pleural fluid","Centrifuge"],procedure:["Centrifuge","Smear","Stain"],result:"Adenocarcinoma cells etc",normal:"Mesothelial cells only",safety:["PPE"],tips:"Large volume increases yield."},

  {id:"ascitic",title:"Ascitic Fluid Cytology",intro:"Detects malignant cells in ascites.",aim:"To diagnose peritoneal malignancy.",principles:"Centrifuged ascitic fluid examined.",materials:["Ascitic fluid","Centrifuge"],procedure:["Centrifuge","Smear","Stain"],result:"Malignant cells",normal:"Mesothelial cells",safety:["PPE"],tips:"Look for adenocarcinoma cells."},

  {id:"thyroid_fnac",title:"Thyroid FNAC",intro:"Diagnoses thyroid nodules.",aim:"To classify thyroid nodule.",principles:"Aspiration of thyroid nodule.",materials:["Needle","Slides"],procedure:["Aspirate nodule","Smear","Stain"],result:"Benign, Follicular, Malignant",normal:"N/A",safety:["Sharps"],tips:"Ultrasound guided for small nodules."},

  {id:"saliva",title:"Salivary Gland FNAC",intro:"Evaluates salivary gland swelling.",aim:"To diagnose salivary gland tumors.",principles:"Aspiration cytology.",materials:["Needle","Slides"],procedure:["Aspirate","Smear","Stain"],result:"Pleomorphic adenoma, Warthin",normal:"N/A",safety:["Gloves"],tips:"Avoid facial nerve."},

  {id:"bone_marrow",title:"Bone Marrow Aspirate Cytology",intro:"Examines bone marrow cells.",aim:"To diagnose hematologic disorders.",principles:"Marrow aspirated and stained.",materials:["Bone marrow needle","Slides"],procedure:["Aspirate marrow","Make smear","Stain"],result:"Cellularity, blast %",normal:"<5% blasts",safety:["Asepsis"],tips:"Used in leukemia diagnosis."}
]},
{id:"parasitology",name:"Parasitology",analyses:[
  {id:"stool_ova",title:"Stool Ova and Parasite Exam",intro:"Detects intestinal parasites in stool.",aim:"To identify ova, cysts and trophozoites.",principles:"Direct saline and iodine wet mount microscopy.",materials:["Fresh stool","Slide","Saline","Iodine","Microscope"],procedure:["Make saline preparation","Make iodine preparation","Examine under 10x and 40x"],result:"Ascaris ova, Giardia cyst, Entamoeba troph",normal:"No parasite seen",safety:["BSL2","Hand washing"],tips:"Submit 3 samples on alternate days for best yield."},

  {id:"thick_malaria",title:"Thick Blood Film for Malaria",intro:"Concentrates blood to detect malaria parasites.",aim:"To detect and quantify malaria parasites.",principles:"RBCs lyse, parasites concentrated in thick film.",materials:["Slide","Giemsa stain","Finger prick blood"],procedure:["Make thick smear","Air dry","Stain 10min","Examine 100x oil"],result:"Plasmodium species and parasite count",normal:"No parasite seen",safety:["Gloves"],tips:"Count parasites per 200 WBCs."},

  {id:"thin_malaria",title:"Thin Blood Film for Malaria",intro:"Identifies Plasmodium species.",aim:"To speciate malaria parasite.",principles:"Intact RBCs allow morphological identification.",materials:["Slide","Methanol","Giemsa","Blood"],procedure:["Make thin smear","Fix with methanol","Stain 20min","Examine"],result:"P.falciparum, P.vivax, P.ovale, P.malariae",normal:"Negative",safety:["Gloves"],tips:"Used alongside thick film."},

  {id:"urine_schisto",title:"Urine for Schistosoma haematobium",intro:"Detects urinary schistosomiasis.",aim:"To find S.haematobium eggs in urine.",principles:"Eggs seen in centrifuged urine sediment.",materials:["Urine","Centrifuge","Slide","Microscope"],procedure:["Collect terminal urine 10am-2pm","Centrifuge","Examine sediment"],result:"S.haematobium eggs",normal:"No eggs",safety:["PPE"],tips:"Eggs have terminal spine."},

  {id:"stool_concentration",title:"Formalin-Ether Concentration",intro:"Increases detection of parasites.",aim:"To concentrate ova and cysts.",principles:"Ether extracts fat and debris, parasites sediment.",materials:["Formalin","Ether","Stool","Tube"],procedure:["Mix stool with formalin","Add ether","Centrifuge","Examine sediment"],result:"Higher yield of parasites",normal:"Negative",safety:["Ether is flammable"],tips:"More sensitive than direct smear."},

  {id:"tape_test",title:"Scotch Tape Test",intro:"Detects Enterobius vermicularis eggs.",aim:"To diagnose pinworm infection.",principles:"Eggs collected from perianal skin on tape.",materials:["Clear tape","Slide","Microscope"],procedure:["Press tape to perianal area on waking","Mount on slide","Examine"],result:"Enterobius eggs",normal:"Negative",safety:["Hygiene"],tips:"Collect before bathing or defecation."},

  {id:"wet_mount",title:"Vaginal Wet Mount",intro:"Examines vaginal discharge.",aim:"To detect Trichomonas and Candida.",principles:"Direct microscopy of vaginal fluid.",materials:["Swab","Slide","Saline","Microscope"],procedure:["Mix swab with saline","Cover slip","Examine immediately"],result:"T.vaginalis, Yeast, Clue cells",normal:"Lactobacilli only",safety:["Gloves"],tips:"Examine within 10 minutes."},

  {id:"blood_filaria",title:"Blood Film for Microfilaria",intro:"Detects filarial worms.",aim:"To diagnose lymphatic filariasis.",principles:"Thick blood film collected at night.",materials:["Slide","Giemsa","Blood"],procedure:["Collect blood 10pm-2am","Make thick film","Stain"],result:"W.bancrofti microfilaria",normal:"Negative",safety:["Gloves"],tips:"Microfilaria are nocturnal."},

  {id:"skin_snip",title:"Skin Snip for Onchocerca",intro:"Detects Onchocerca volvulus.",aim:"To diagnose river blindness.",principles:"Skin incubated in saline, microfilaria emerge.",materials:["Scalpel","Saline","Microscope"],procedure:["Take skin snip","Incubate in saline","Examine for mf"],result:"O.volvulus microfilaria",normal:"Negative",safety:["Sharps"],tips:"Take from iliac crest."},

  {id:"toxo_serology",title:"Toxoplasma IgG/IgM",intro:"Detects Toxoplasma gondii infection.",aim:"To diagnose toxoplasmosis.",principles:"ELISA detects IgG and IgM antibodies.",materials:["Toxo ELISA kit","Serum"],procedure:["Add serum","Incubate","Wash","Read"],result:"IgG+, IgM+",normal:"Negative",safety:["PPE"],tips:"IgM = recent infection. Important in pregnancy."}
]},
   {id:"chempath",name:"Chemical Pathology",analyses:[
  {id:"lft",title:"Liver Function Test",intro:"LFT assesses liver synthetic, excretory and metabolic function. Used in hepatitis, cirrhosis and drug toxicity.",aim:"To measure ALT, AST, ALP, Bilirubin, Total Protein and Albumin.",principles:"ALT/AST: Kinetic method. Bilirubin: Diazotization. Protein: Biuret reaction. Albumin: BCG dye binding.",materials:["LFT reagent kit","Serum","Spectrophotometer","Cuvettes"],procedure:["Collect venous blood, separate serum","Pipette serum and reagents as per kit","Incubate at 37°C","Read absorbance at specific wavelength","Calculate concentration"],result:"Enzyme activity in IU/L, Bilirubin in mg/dL, Protein in g/dL",normal:"ALT:<40 AST:<40 ALP:40-120 T.Bili:<1.2 T.Protein:6-8 Albumin:3.5-5.0",safety:["Wear PPE","Dispose reagents properly"],tips:"AST:ALT >2 suggests alcoholic liver disease. ALP + Bilirubin high = cholestasis."},

  {id:"rft",title:"Renal Function Test",intro:"RFT evaluates kidney filtration and waste excretion.",aim:"To measure Urea, Creatinine, Uric acid and Electrolytes.",principles:"Urea: Urease method. Creatinine: Jaffe reaction. Electrolytes: Ion Selective Electrode.",materials:["RFT kit","ISE machine","Serum"],procedure:["Collect serum","Run on analyzer","Record results"],result:"mg/dL and mmol/L",normal:"Urea:15-40 Creatinine:0.6-1.2 Na:135-145 K:3.5-5.0",safety:["Universal precautions"],tips:"Creatinine is more specific for GFR. BUN:Creat ratio >20:1 suggests pre-renal cause."},

  {id:"lipid",title:"Lipid Profile",intro:"Assesses cardiovascular risk by measuring blood lipids.",aim:"To measure Total Cholesterol, Triglyceride, HDL and calculate LDL.",principles:"Enzymatic colorimetric method. LDL = TC - HDL - TG/5",materials:["Lipid kit","Fasting serum","Spectro"],procedure:["12hr fasting sample","Add reagents","Incubate","Read"],result:"mg/dL",normal:"TC<200 TG<150 HDL>40 LDL<100",safety:["PPE"],tips:"Fasting 9-12hrs. Non-fasting TG unreliable."},

  {id:"fbg",title:"Fasting Blood Glucose",intro:"Measures blood glucose to screen for diabetes.",aim:"To determine plasma glucose concentration.",principles:"Glucose oxidase-peroxidase method produces colored dye.",materials:["Glucose kit","Fluoride oxalate tube","Spectro"],procedure:["Collect fasting blood","Separate plasma","Mix with reagent","Incubate 10min","Read 500nm"],result:"mg/dL",normal:"Fasting:70-100 Impaired:101-125 Diabetic:>126",safety:["Sharps disposal"],tips:"Use fluoride tube to prevent glycolysis. RBG >200 with symptoms = Diabetes."},

  {id:"hba1c",title:"Glycated Hemoglobin HbA1c",intro:"Reflects average blood glucose over 3 months.",aim:"To monitor long term glycemic control.",principles:"HbA1c is glucose bound to hemoglobin. Measured by HPLC or immunoassay.",materials:["EDTA blood","HbA1c analyzer"],procedure:["Collect EDTA blood","Load on analyzer","Run test"],result:"%",normal:"Normal:<5.7 Pre-diabetic:5.7-6.4 Diabetic:>6.5",safety:["Blood safety"],tips:"Not affected by recent meals. Used for diabetes monitoring."},

  {id:"electrolytes",title:"Serum Electrolytes",intro:"Na, K, Cl, HCO3 maintain fluid and acid-base balance.",aim:"To measure electrolyte levels.",principles:"Ion Selective Electrode measures ion activity.",materials:["ISE analyzer","Serum"],procedure:["Load sample","Calibrate","Run"],result:"mmol/L",normal:"Na:135-145 K:3.5-5.0 Cl:98-106 HCO3:22-28",safety:["Machine safety"],tips:"Hemolysis causes pseudohyperkalemia. Critical K >6.5 or <2.5."},

  {id:"cardiac",title:"Cardiac Troponin I",intro:"Troponin I is specific for myocardial injury.",aim:"To diagnose acute myocardial infarction.",principles:"Immunoassay. Antibodies bind to cardiac troponin I.",materials:["Troponin kit","Serum"],procedure:["Add serum to test cassette","Wait 15min","Read"],result:"Positive or Negative",normal:"<0.04 ng/mL",safety:["PPE"],tips:"Rises 3-6hrs, peaks 24hrs, stays 10-14 days. Gold standard for MI."},

  {id:"thyroid",title:"Thyroid Function Test",intro:"T3, T4, TSH assess thyroid status.",aim:"To measure TSH, Free T3 and Free T4.",principles:"Competitive chemiluminescent immunoassay.",materials:["TFT kit","Serum","Analyzer"],procedure:["Add serum","Incubate","Wash","Read luminescence"],result:"μIU/mL and ng/dL",normal:"TSH:0.4-4.0 FT4:0.8-1.8 FT3:2.3-4.2",safety:["Gloves"],tips:"TSH first line. High TSH + Low T4 = Hypothyroidism."},

  {id:"calcium",title:"Serum Calcium",intro:"Calcium important for nerve, muscle and bone.",aim:"To measure total and ionized calcium.",principles:"Forms colored complex with cresolphthalein.",materials:["Calcium kit","Serum"],procedure:["Mix","Incubate","Read 570nm"],result:"mg/dL",normal:"Total:8.5-10.5 Ionized:4.6-5.3",safety:["Reagent caution"],tips:"Correct for albumin: Corrected Ca = Ca + 0.8(4-Alb)"},

  {id:"amylase",title:"Serum Amylase and Lipase",intro:"Pancreatic enzymes elevated in pancreatitis.",aim:"To measure amylase and lipase.",principles:"Amylase: Hydrolysis of starch. Lipase: Hydrolysis of triglyceride.",materials:["Amylase/Lipase kit","Serum"],procedure:["Mix","Incubate","Read"],result:"IU/L",normal:"Amylase:30-110 Lipase:10-140",safety:["PPE"],tips:"Lipase more specific and stays elevated longer than amylase."}
]}
  ],
  questions: [
  {id:1,q:"What is the normal PCV range for adult male?",options:["30-40%","40-54%","55-65%","35-45%"],answer:1,exp:"Normal PCV for males is 40-54%. Females: 37-47%. Low PCV indicates anemia."},
  {id:2,q:"Which method is used for Hemoglobin estimation in Sahli's method?",options:["Cyanmethemoglobin","Acid hematin","Oxyhemoglobin","Carboxyhemoglobin"],answer:1,exp:"Sahli method converts Hb to acid hematin with N/10 HCl and color is matched."},
  {id:3,q:"ESR is markedly raised in:",options:["Polycythemia","Inflammation","Dehydration","Hemoconcentration"],answer:1,exp:"ESR increases in inflammation due to fibrinogen and immunoglobulins causing rouleaux formation."},
  {id:4,q:"Normal WBC count range is:",options:["2000-5000","4000-11000","12000-20000","5000-15000"],answer:1,exp:"Normal total WBC count is 4000-11000 cells/μL."},
  {id:5,q:"Platelets are counted using:",options:["WBC pipette","Platelet pipette and Rees-Ecker fluid","RBC pipette","Direct method"],answer:1,exp:"Platelet count uses 1:100 dilution with Rees-Ecker fluid in Neubauer chamber."},
  {id:6,q:"Glucose oxidase method measures:",options:["Protein","Glucose","Urea","Creatinine"],answer:1,exp:"Glucose oxidase converts glucose to gluconic acid and H2O2 which forms colored dye."},
  {id:7,q:"Jaffe reaction is used for:",options:["Urea","Creatinine","Bilirubin","Cholesterol"],answer:1,exp:"Creatinine reacts with alkaline picrate to form orange-red complex."},
  {id:8,q:"ALT is more specific for:",options:["Heart","Kidney","Liver","Muscle"],answer:2,exp:"ALT is primarily found in liver. Raised in hepatitis."},
  {id:9,q:"Normal fasting blood glucose is:",options:["50-70","70-100","100-140","140-180"],answer:1,exp:"Fasting glucose 70-100 mg/dL. >126 on 2 occasions = Diabetes."},
  {id:10,q:"HbA1c reflects average glucose for:",options:["1 week","2 weeks","3 months","6 months"],answer:2,exp:"HbA1c reflects average glucose over 120 days, approx 3 months."},
  {id:11,q:"Principle of Gram stain is based on:",options:["Cell wall","Capsule","Flagella","Nucleus"],answer:0,exp:"Thick peptidoglycan in Gram +ve retains crystal violet."},
  {id:12,q:"ZN stain is used for:",options:["E.coli","Staphylococcus","Mycobacterium","Candida"],answer:2,exp:"ZN stains acid-fast bacilli like TB due to mycolic acid."},
  {id:13,q:"Significant bacteriuria is:",options:[">1000 CFU/mL",">10000 CFU/mL",">100000 CFU/mL",">1000000 CFU/mL"],answer:2,exp:">100,000 CFU/mL in clean catch is significant."},
  {id:14,q:"Blood culture is used to diagnose:",options:["UTI","Sepsis","Pneumonia","Diarrhea"],answer:1,exp:"Blood culture detects bacteremia and sepsis."},
  {id:15,q:"Kirby-Bauer test is for:",options:["Identification","Sensitivity","Culture","Staining"],answer:1,exp:"Disk diffusion test to check antibiotic sensitivity."},
  {id:16,q:"HIV rapid test detects:",options:["Antigen","Antibody","RNA","DNA"],answer:1,exp:"Most rapid tests detect HIV 1/2 antibodies."},
  {id:17,q:"HBsAg indicates:",options:["Immunity","Past infection","Current infection","Vaccination"],answer:2,exp:"HBsAg = current HBV infection."},
  {id:18,q:"Widal test is for:",options:["Typhoid","Malaria","TB","Hepatitis"],answer:0,exp:"Detects anti-O and anti-H antibodies against Salmonella."},
  {id:19,q:"CRP is an:",options:["Antibody","Enzyme","Acute phase protein","Hormone"],answer:2,exp:"CRP rises within 6hrs of inflammation."},
  {id:20,q:"ASOT is raised in:",options:["Strep infection","Staph infection","E.coli","Salmonella"],answer:0,exp:"Anti-streptolysin O titer rises after Group A Strep."},
  {id:21,q:"Fixation is done with:",options:["Alcohol","Acetone","10% Formalin","Xylene"],answer:2,exp:"10% buffered formalin is routine fixative."},
  {id:22,q:"H&E stains nuclei:",options:["Pink","Blue","Yellow","Red"],answer:1,exp:"Hematoxylin stains nuclei blue, Eosin stains cytoplasm pink."},
  {id:23,q:"IHC is used to detect:",options:["Bacteria","Antigen","DNA","RNA"],answer:1,exp:"Immunohistochemistry detects specific antigens using antibodies."},
  {id:24,q:"Frozen section is for:",options:["Routine","Rapid diagnosis","Special stain","Culture"],answer:1,exp:"Frozen section gives diagnosis within 15 minutes during surgery."},
  {id:25,q:"ABO grouping is based on:",options:["Antigens on RBC","Antibodies in serum","Both","None"],answer:2,exp:"Cell grouping + Serum grouping must agree."},
  {id:26,q:"Crossmatching is done to prevent:",options:["Infection","Transfusion reaction","Clotting","Hemolysis"],answer:1,exp:"Checks compatibility between donor and recipient."},
  {id:27,q:"DAT is positive in:",options:["Iron deficiency","AIHA","Thalassemia","Sickle cell"],answer:1,exp:"Direct Coombs detects antibodies on RBCs in autoimmune hemolytic anemia."},
  {id:28,q:"Blood is stored at:",options:["Room temp","2-6°C","-20°C","37°C"],answer:1,exp:"PRBC stored at 2-6°C for 42 days."},
  {id:29,q:"Pap smear screens for:",options:["Breast cancer","Cervical cancer","Ovarian cancer","Uterine cancer"],answer:1,exp:"Pap smear detects cervical precancerous lesions."},
  {id:30,q:"FNAC is used for:",options:["Blood","Lump","Urine","Stool"],answer:1,exp:"Fine needle aspiration cytology for palpable lumps."},
  {id:31,q:"Thick film is used for:",options:["Species ID","Parasite concentration","Culture","Sensitivity"],answer:1,exp:"Thick film lyses RBCs to concentrate parasites."},
  {id:32,q:"Malaria parasite is identified in:",options:["Thick film","Thin film","Both","None"],answer:2,exp:"Thick for detection, Thin for species."},
  {id:33,q:"S.haematobium eggs are found in:",options:["Stool","Urine","Blood","CSF"],answer:1,exp:"Urinary schistosomiasis eggs in urine with terminal spine."},
  {id:34,q:"Scotch tape test is for:",options:["Ascaris","Hookworm","Pinworm","Tapeworm"],answer:2,exp:"Enterobius vermicularis eggs collected from perianal area."},
  {id:35,q:"Microfilaria are collected at:",options:["Morning","Afternoon","Night","Anytime"],answer:2,exp:"W.bancrofti microfilaria are nocturnal 10pm-2am."},
  {id:36,q:"PCR is used to detect:",options:["Antibody","Antigen","DNA/RNA","Protein"],answer:2,exp:"PCR amplifies nucleic acid."},
  {id:37,q:"NS1 antigen is for:",options:["HIV","Dengue","Hepatitis","COVID"],answer:1,exp:"Dengue NS1 appears in first week."},
  {id:38,q:"RT-PCR is gold standard for:",options:["HIV","TB","COVID","Malaria"],answer:2,exp:"SARS-CoV-2 RT-PCR from NP swab."},
  {id:39,q:"Toxoplasma IgM indicates:",options:["Past infection","Recent infection","Immunity","Vaccination"],answer:1,exp:"IgM appears early, IgG persists."},
  {id:40,q:"Corrected calcium formula is:",options:["Ca + 0.8(4-Alb)","Ca - 0.8(4-Alb)","Ca x Alb","Ca/Alb"],answer:0,exp:"Correct for low albumin: Ca + 0.8(4-Alb)"}
  ],
  faqs:[
    {q:"What is LabGuru?",a:"LabGuru is a Medical Laboratory Science (MLS) learning companion covering principles, procedures, results and exam tips across Hematology, Chemistry, Microbiology, Immunology and more."},
    {q:"How many analyses can I read for free?",a:"You can open a limited number of analyses for free. Once you reach the limit, you can unlock Premium for unlimited access."},
    {q:"What does Premium include?",a:"Unlimited analyses, the full unit converter, a synced progress dashboard, study reminders, new-content alerts, and offline access — billed ₦2,200 every 2 months."},
    {q:"Why do I need to sign in with Google?",a:"Sign-in is only required to subscribe to Premium or enable notifications, so your subscription status and progress can sync across your devices. Everything else works fully signed out."},
    {q:"Does LabGuru work offline?",a:"Yes — once you've opened the app online at least once, it caches itself and works fully offline. Your progress is saved locally and synced to the cloud next time you're online and signed in."},
    {q:"How do I cancel my subscription?",a:"You can cancel anytime — Paystack sends you a receipt email with a manage-subscription link, or you can contact support."}
  ]
}
