const LAB_DATA = {
  settings:{freeLimit:5,premiumPrice:2200,paystackPublicKey:"pk_test_YOUR_KEY"},
  units:[
    {id:"hematology",name:"Hematology",analyses:[
      {id:"pcv",title:"Packed Cell Volume (PCV)",intro:"PCV measures the volume of red blood cells expressed as a percentage of total blood volume. It is used to assess anemia, polycythemia and dehydration.",aim:"To determine the percentage of red blood cells in whole blood.",principles:"Anticoagulated blood is centrifuged at high speed. Red cells pack at the bottom. The ratio of packed cells to total blood gives PCV.",materials:["EDTA blood sample","Microhematocrit tubes","Clay sealant","Microhematocrit centrifuge","Reader"],procedure:["Mix blood well","Fill tube 3/4 and seal end","Centrifuge at 10,000rpm for 5min","Read PCV with reader"],result:"Red cell column as % of total column",normal:"Male: 40-54%. Female: 37-47%",safety:["Wear PPE","Dispose sharps","Decontaminate area"],tips:"Rule of 3: Hb x 3 ≈ PCV. Low PCV = anemia. High PCV = dehydration."},
      {id:"hb",title:"Hemoglobin Estimation - Sahli Method",intro:"Hemoglobin carries oxygen. Sahli method converts Hb to acid hematin and color is matched.",aim:"To estimate hemoglobin concentration.",principles:"Hb + HCl → Acid hematin. Color intensity compared to standard.",materials:["Sahli apparatus","N/10 HCl","Hb pipette","Distilled water"],procedure:["Put HCl to 20 mark","Add 20μL blood","Wait 10min","Add water till color match","Read g/dL"],result:"g/dL directly from tube",normal:"Male:13.5-17.5 Female:12-15.5",safety:["Handle HCl carefully"],tips:"Wait full 10min. Rushing gives low result."},
      {id:"esr",title:"Erythrocyte Sedimentation Rate",intro:"ESR measures rate RBCs settle in 1hr. Increased in inflammation.",aim:"To measure ESR.",principles:"Inflammatory proteins cause RBC aggregation and faster settling.",materials:["Westergren tube","ESR stand","Sodium citrate blood"],procedure:["Dilute blood 4:1 with citrate","Fill to 200mm","Stand 1hr","Read mm"],result:"mm/hr",normal:"M:<15 F:<20",safety:["Universal precautions"],tips:"Non-specific test. Used to monitor disease activity."},
      {id:"twbc",title:"Total White Blood Cell Count",intro:"Counts all WBCs. Elevated in infection, leukemia.",aim:"To determine WBC count per μL.",principles:"Blood diluted 1:20, WBCs counted in Neubauer chamber.",materials:["WBC pipette","Turks fluid","Counting chamber"],procedure:["Dilute blood","Load chamber","Count 4 squares","Calculate x50"],result:"Cells/μL",normal:"4000-11000",safety:["Wear gloves"],tips:"Turks lyses RBCs and stains WBC nuclei."},
      {id:"platelet",title:"Platelet Count",intro:"Platelets aid clotting. Low causes bleeding.",aim:"To count platelets.",principles:"Blood diluted 1:100, counted in chamber.",materials:["Platelet pipette","Rees-Ecker fluid","Chamber"],procedure:["Dilute","Load","Count 5 squares","x1000"],result:"/μL",normal:"150000-450000",safety:["Avoid aerosols"],tips:"Clumping causes false low."},
      {id:"diff",title:"Differential WBC Count",intro:"Percentage of each WBC type.",aim:"To identify WBC types.",principles:"Stained film examined, 100 cells counted.",materials:["Slides","Leishman stain","Oil immersion"],procedure:["Make film","Stain","Count 100 WBCs"],result:"% Neut, Lymph, Mono, Eos, Baso",normal:"N:40-75 L:20-45",safety:["Handle slides"],tips:"Good film = good diff."},
      {id:"film",title:"Peripheral Blood Film",intro:"Assesses RBC, WBC, Platelet morphology.",aim:"To prepare quality blood film.",principles:"Thin spread of blood for microscopy.",materials:["2 slides","Blood","Stain"],procedure:["Drop blood","Spread at 45°","Air dry","Stain"],result:"Thin film with feather edge",normal:"N/A",safety:["No mouth pipetting"],tips:"Feather edge must be smooth."},
      {id:"retic",title:"Reticulocyte Count",intro:"Young RBCs. Shows marrow activity.",aim:"To count retics.",principles:"New methylene blue stains RNA reticulum.",materials:["New methylene blue","Tube","Slides"],procedure:["Mix 1:1","Incubate 15min","Make film","Count 1000 RBCs"],result:"%",normal:"0.5-2.5%",safety:["Dye stains"],tips:"High in hemolytic anemia."},
      {id:"bt",title:"Bleeding Time",intro:"Tests platelet and capillary function.",aim:"To measure bleeding time.",principles:"Standard incision, time to stop.",materials:["Lancet","Filter paper","Timer"],procedure:["Clean ear","3mm incision","Blot 30s","Stop when dry"],result:"Minutes",normal:"2-9min",safety:["Sharps disposal"],tips:"Prolonged in thrombocytopenia."},
      {id:"ct",title:"Clotting Time",intro:"Intrinsic pathway function.",aim:"To measure clotting time.",principles:"Blood in glass tube clots.",materials:["Glass tube","37°C bath","Lancet"],procedure:["Collect blood","Place in bath","Tilt 30s","Note clot"],result:"Minutes",normal:"5-10min",safety:["Blood handling"],tips:"Prolonged in hemophilia."}
    ]},
    {id:"chemistry",name:"Clinical Chemistry",analyses:[
      {id:"glucose",title:"Blood Glucose",intro:"Measures blood sugar. Key in diabetes.",aim:"To estimate glucose.",principles:"Glucose oxidase → H2O2 → colored dye.",materials:["Glucose reagent","Spectro","Serum"],procedure:["Mix","Incubate 10min","Read 500nm"],result:"Absorbance",normal:"Fasting:70-100mg/dL",safety:["Reagent caution"],tips:"Fasting sample best."},
      {id:"urea",title:"Blood Urea",intro:"End product of protein metabolism. Kidney function test.",aim:"To measure urea.",principles:"Urease converts urea to ammonia.",materials:["Urea kit","Serum"],procedure:["Mix reagent","Incubate","Read"],result:"mg/dL",normal:"15-40",safety:["PPE"],tips:"High in renal failure."},
      {id:"creatinine",title:"Serum Creatinine",intro:"Muscle metabolism product. GFR marker.",aim:"To measure creatinine.",principles:"Jaffe reaction with alkaline picrate.",materials:["Creatinine kit","Serum"],procedure:["Mix","Wait","Read 520nm"],result:"mg/dL",normal:"0.6-1.2",safety:["Gloves"],tips:"More specific than urea."},
      {id:"alt",title:"Alanine Aminotransferase",intro:"Liver enzyme. Raised in hepatitis.",aim:"To measure ALT.",principles:"ALT catalyzes transfer of amino group.",materials:["ALT kit","Serum","Spectro"],procedure:["Mix","Incubate","Read 340nm"],result:"IU/L",normal:"<40",safety:["PPE"],tips:"More liver specific than AST."},
      {id:"ast",title:"Aspartate Aminotransferase",intro:"Liver and cardiac enzyme.",aim:"To measure AST.",principles:"Similar to ALT.",materials:["AST kit","Serum"],procedure:["Mix","Incubate","Read"],result:"IU/L",normal:"<40",safety:["Gloves"],tips:"Also raised in MI."},
      {id:"bilirubin",title:"Total & Direct Bilirubin",intro:"Hemoglobin breakdown product.",aim:"To measure bilirubin.",principles:"Diazotization with sulfanilic acid.",materials:["Bilirubin kit","Serum"],procedure:["Add reagent","Incubate","Read"],result:"mg/dL",normal:"Total:<1.2 Direct:<0.3",safety:["Light sensitive"],tips:"High = jaundice."},
      {id:"cholesterol",title:"Serum Cholesterol",intro:"Lipid profile component.",aim:"To measure cholesterol.",principles:"Cholesterol esterase → H2O2 → dye.",materials:["Cholesterol kit","Serum"],procedure:["Mix","Incubate","Read"],result:"mg/dL",normal:"<200",safety:["PPE"],tips:"Fasting sample."},
      {id:"protein",title:"Total Protein",intro:"Albumin + Globulin.",aim:"To measure total protein.",principles:"Biuret reaction → violet complex.",materials:["Biuret reagent","Serum"],procedure:["Mix","Incubate","Read 540nm"],result:"g/dL",normal:"6-8",safety:["Caustic reagent"],tips:"Low in malnutrition."},
      {id:"electrolytes",title:"Serum Electrolytes",intro:"Na, K, Cl, HCO3.",aim:"To measure electrolytes.",principles:"Ion selective electrode.",materials:["ISE machine","Serum"],procedure:["Load sample","Run"],result:"mmol/L",normal:"Na:135-145 K:3.5-5.0",safety:["Machine safety"],tips:"Critical for fluid balance."},
      {id:"amylase",title:"Serum Amylase",intro:"Pancreatic enzyme.",aim:"To measure amylase.",principles:"Hydrolysis of starch substrate.",materials:["Amylase kit","Serum"],procedure:["Mix","Incubate","Read"],result:"IU/L",normal:"30-110",safety:["Gloves"],tips:"High in pancreatitis."}
    ]},
    {id:"microbiology",name:"Medical Microbiology",analyses:[
      {id:"gs",title:"Gram Stain",intro:"Differentiates bacteria into Gram + and -.",aim:"To stain bacteria.",principles:"Crystal violet-iodine complex retained by thick peptidoglycan.",materials:["Slide","Crystal violet","Iodine","Alcohol","Safranin"],procedure:["Make smear","Heat fix","CV 1min","Iodine 1min","Alcohol decolorize","Safranin 30s"],result:"Purple=Gram+ Pink=Gram-",normal:"N/A",safety:["Biosafety"],tips:"Do not over-decolorize."},
      {id:"zn",title:"Ziehl-Neelsen Stain",intro:"Detects acid-fast bacilli like TB.",aim:"To demonstrate AFB.",principles:"Carbol fuchsin penetrates waxy cell wall.",materials:["Slide","Carbol fuchsin","Acid alcohol","Methylene blue"],procedure:["Smear","Heat stain","Acid wash","Counterstain"],result:"Red=AFB Blue=other",normal:"Negative",safety:["BSL2"],tips:"Heat is key for penetration."},
      {id:"culture",title:"Urine Culture",intro:"Detects UTI pathogens.",aim:"To isolate bacteria from urine.",principles:"Quantitative culture on CLED.",materials:["CLED plate","Loop","Incubator"],procedure:["Inoculate 1μL","Incubate 24h","Count colonies"],result:"CFU/mL",normal:"<10000",safety:["BSL2"],tips:">100000 = significant."},
      {id:"msu",title:"Midstream Urine Collection",intro:"Clean catch to avoid contamination.",aim:"To collect urine aseptically.",principles:"Clean urethral opening before collection.",materials:["Sterile container","Wipes"],procedure:["Clean genitals","Start void","Collect midstream"],result:"Clean sample",normal:"N/A",safety:["Patient education"],tips:"First morning sample best."},
      {id:"bloodculture",title:"Blood Culture",intro:"Detects bacteremia.",aim:"To isolate organisms from blood.",principles:"Blood inoculated into broth.",materials:["Blood culture bottle","Syringe"],procedure:["Aseptic draw","Inoculate","Incubate 7days"],result:"Growth/No growth",normal:"No growth",safety:["Strict asepsis"],tips:"2 sets from different sites."},
      {id:"sputum",title:"Sputum Culture",intro:"Respiratory pathogens.",aim:"To isolate respiratory bacteria.",principles:"Culture on blood and chocolate agar.",materials:["Sputum container","Agar plates"],procedure:["Collect sputum","Inoculate","Incubate"],result:"Organism ID",normal:"Normal flora",safety:["TB precautions"],tips:"Reject saliva."},
      {id:"wound",title:"Wound Swab Culture",intro:"Identifies wound pathogens.",aim:"To isolate bacteria.",principles:"Swab inoculated on media.",materials:["Swab","Media"],procedure:["Swab wound","Plate","Incubate"],result:"Organism + sensitivity",normal:"No pathogen",safety:["PPE"],tips:"Take from depth."},
      {id:"stool",title:"Stool Culture",intro:"Enteric pathogens.",aim:"To isolate Salmonella, Shigella.",principles:"Selective media: XLD, SS.",materials:["Stool container","Media"],procedure:["Inoculate","Incubate","Identify"],result:"Pathogen ID",normal:"Normal flora",safety:["BSL2"],tips:"Fresh sample."},
      {id:"csf",title:"CSF Analysis",intro:"Meningitis diagnosis.",aim:"To analyze CSF.",principles:"Cell count, chemistry, culture.",materials:["CSF tube","Chamber"],procedure:["Cell count","Glucose","Protein","Culture"],result:"Cells, protein, glucose",normal:"<5 cells, Glucose 50-80",safety:["BSL2"],tips:"Urgent processing."},
      {id:"sensitivity",title:"Antibiotic Sensitivity",intro:"Determines drug effectiveness.",aim:"To test antibiotic susceptibility.",principles:"Kirby-Bauer disk diffusion.",materials:["Mueller-Hinton agar","Antibiotic disks"],procedure:["Inoculate","Add disks","Incubate","Measure zones"],result:"S, I, R",normal:"N/A",safety:["BSL2"],tips:"Use standard inoculum."}
    ]},
       {id:"immunology",name:"Immunology",analyses:[
  {id:"hiv",title:"HIV Rapid Test",intro:"The HIV rapid test detects antibodies to HIV-1 and HIV-2 in blood. It is used for screening and early detection of HIV infection.",aim:"To qualitatively detect HIV antibodies in human serum or plasma.",principles:"It is a lateral flow chromatographic immunoassay. If HIV antibodies are present, they bind to antigen-coated colloidal gold and form a visible line.",materials:["HIV rapid test kit","Lancing device","Capillary tube","Buffer","Timer"],procedure:["Perform hand hygiene and wear gloves","Collect finger-prick blood","Add 1 drop of blood to sample well","Add 2 drops of buffer","Read result at 15 minutes"],result:"1 line = Negative. 2 lines = Reactive. No control line = Invalid",normal:"Non-reactive",safety:["Universal precautions","Dispose sharps in safety box","Decontaminate surface"],tips:"Always confirm reactive results with ELISA and Western Blot. Window period is 3 months."},
  
  {id:"hbsag",title:"Hepatitis B Surface Antigen Test",intro:"HBsAg test detects the surface antigen of Hepatitis B virus. It indicates current HBV infection.",aim:"To detect HBsAg in serum or plasma.",principles:"Sandwich ELISA or immunochromatography. HBsAg binds to anti-HBs antibodies on the test strip.",materials:["HBsAg test kit","Serum sample","Pipette","Timer"],procedure:["Add 50μL of serum to sample well","Add buffer","Incubate 15 minutes","Read result"],result:"1 line = Negative. 2 lines = Positive",normal:"Negative",safety:["Handle blood as infectious","Use PPE"],tips:"Vaccinated persons may be HBsAb positive but HBsAg negative."},

  {id:"widal",title:"Widal Test",intro:"Widal test detects agglutinating antibodies against Salmonella typhi and paratyphi in typhoid fever.",aim:"To detect anti-O and anti-H antibodies against Salmonella.",principles:"Patient serum is mixed with antigen suspensions. Agglutination indicates presence of antibodies.",materials:["Widal antigen kit","Serum","Test tubes","Water bath"],procedure:["Make serial dilutions of serum 1:20 to 1:640","Add antigen","Incubate at 37°C for 18-24hrs","Observe agglutination"],result:"Titer ≥1:160 considered significant",normal:"<1:80",safety:["Handle serum carefully"],tips:"Single high titer is not diagnostic. 4-fold rise in paired sera is better."},

  {id:"ra",title:"Rheumatoid Factor Test",intro:"RF is an autoantibody against IgG. It is present in Rheumatoid Arthritis.",aim:"To detect Rheumatoid Factor in serum.",principles:"Latex particles coated with human IgG agglutinate in presence of RF.",materials:["RF latex kit","Serum","Slide","Mixer"],procedure:["Place 1 drop serum and 1 drop reagent on slide","Mix and rotate 2 minutes","Observe agglutination"],result:"Agglutination = Positive",normal:"<20 IU/mL",safety:["Wear gloves"],tips:"RF can be positive in other autoimmune diseases and infections."},

  {id:"crp",title:"C-Reactive Protein",intro:"CRP is an acute phase protein that rises rapidly in inflammation and infection.",aim:"To measure CRP levels in serum.",principles:"Latex agglutination. CRP binds to anti-CRP antibodies on latex particles.",materials:["CRP kit","Serum","Slide"],procedure:["Mix serum and reagent","Rotate 2 minutes","Observe agglutination"],result:"Positive if agglutination. Quantitate by dilution",normal:"<10 mg/L",safety:["Universal precautions"],tips:"Rises within 6 hours of inflammation. Falls quickly with treatment."},

  {id:"asot",title:"Anti-Streptolysin O Titer",intro:"ASOT detects antibodies against Streptolysin O produced by Group A Streptococcus.",aim:"To detect ASOT in serum.",principles:"Latex particles coated with streptolysin O agglutinate with anti-streptolysin antibodies.",materials:["ASOT kit","Serum","Slide"],procedure:["Mix serum and latex reagent","Rotate 2 minutes","Read agglutination"],result:"Titer in IU/mL",normal:"<200 IU/mL",safety:["Wear PPE"],tips:"Elevated 1-3 weeks after strep infection. Used in rheumatic fever diagnosis."},

  {id:"malaria_rdt",title:"Malaria Rapid Diagnostic Test",intro:"RDT detects Plasmodium antigens HRP2 and pLDH in blood.",aim:"To diagnose malaria infection.",principles:"Immunochromatographic test. Parasite antigen binds to antibodies on test strip.",materials:["Malaria RDT kit","Blood","Buffer","Lancet"],procedure:["Collect blood","Add to sample pad","Add buffer","Read at 15 minutes"],result:"HRP2 line = P.falciparum. pLDH line = other species",normal:"Negative",safety:["Sharps disposal"],tips:"Always confirm with blood film. HRP2 can persist after treatment."},

  {id:"pregnancy",title:"Urine Pregnancy Test",intro:"Detects human chorionic gonadotropin hormone in urine.",aim:"To confirm pregnancy.",principles:"Anti-hCG antibodies bind to hCG in urine producing colored line.",materials:["Pregnancy strip","Urine container"],procedure:["Collect early morning urine","Dip strip for 10 seconds","Read at 5 minutes"],result:"2 lines = Positive",normal:"Negative",safety:["Hygiene"],tips:"Most sensitive in first morning urine."},

  {id:"vdrl",title:"VDRL Test",intro:"VDRL screens for syphilis by detecting reagin antibodies.",aim:"To screen for syphilis.",principles:"Cardiolipin antigen reacts with antibodies forming flocculation.",materials:["VDRL antigen","Serum","Rotator","Slide"],procedure:["Heat inactivate serum","Add antigen","Rotate 4 minutes","Examine microscopically"],result:"Reactive or Non-reactive",normal:"Non-reactive",safety:["Blood precautions"],tips:"Biological false positives occur. Confirm with TPHA."},

  {id:"coombs",title:"Direct Coombs Test",intro:"Detects antibodies or complement attached to RBC surface.",aim:"To detect in-vivo sensitization of RBCs.",principles:"Anti-human globulin binds to IgG or complement on RBCs causing agglutination.",materials:["Coombs serum","Patient RBCs","Test tube","Centrifuge"],procedure:["Wash RBCs 3 times","Add Coombs reagent","Centrifuge","Look for agglutination"],result:"Agglutination = Positive",normal:"Negative",safety:["Blood safety"],tips:"Used in hemolytic disease of newborn and autoimmune hemolytic anemia."}
]},
{id:"histopathology",name:"Histopathology",analyses:[
  {id:"fixation",title:"Tissue Fixation",intro:"Fixation preserves tissue structure and prevents autolysis and putrefaction.",aim:"To preserve tissue in near life-like state.",principles:"10% Formalin cross-links proteins and inactivates enzymes.",materials:["10% Buffered formalin","Specimen container","Tissue"],procedure:["Place tissue immediately in formalin","Tissue to fixative ratio 1:10","Fix for 24-48 hours"],result:"Firm, preserved tissue",normal:"N/A",safety:["Use fume hood","Wear gloves"],tips:"Do not overfix. It can interfere with IHC."},

  {id:"processing",title:"Tissue Processing",intro:"Processing removes water and infiltrates tissue with paraffin.",aim:"To make tissue suitable for sectioning.",principles:"Dehydration with alcohol, clearing with xylene, infiltration with paraffin.",materials:["Tissue processor","Alcohol grades","Xylene","Paraffin"],procedure:["Dehydrate 70% to 100% alcohol","Clear in xylene","Infiltrate in paraffin","Embed"],result:"Paraffin block",normal:"N/A",safety:["Xylene is toxic"],tips:"Standard cycle is 12-16 hours."},

  {id:"microtomy",title:"Microtomy and Sectioning",intro:"Cutting thin sections from paraffin block for microscopy.",aim:"To obtain 4-5μm sections.",principles:"Paraffin block is cut using a microtome.",materials:["Microtome","Paraffin block","Water bath","Slides"],procedure:["Trim block","Cut ribbon of sections","Float on 45°C water bath","Mount on slide"],result:"Thin tissue ribbon",normal:"N/A",safety:["Sharp blades"],tips:"Water bath temperature is critical to avoid wrinkles."},

  {id:"he",title:"Hematoxylin and Eosin Staining",intro:"H&E is the routine stain in histopathology.",aim:"To stain nuclei and cytoplasm for diagnosis.",principles:"Hematoxylin stains nuclei blue. Eosin stains cytoplasm pink.",materials:["H&E reagents","Staining jars","Slides"],procedure:["Deparaffinize","Hematoxylin 5min","Acid alcohol dip","Eosin 1min","Dehydrate and mount"],result:"Blue nuclei, Pink cytoplasm",normal:"N/A",safety:["Reagent handling"],tips:"Good differentiation is key to nuclear detail."},

  {id:"fnac",title:"Fine Needle Aspiration Cytology",intro:"FNAC obtains cells from a lesion for diagnosis.",aim:"To prepare cytological smears.",principles:"Cells are aspirated and smeared on slide then stained.",materials:["Needle","Syringe","Slides","Stains"],procedure:["Aspirate lesion","Express material on slide","Smear","Fix and stain"],result:"Cellular smear",normal:"N/A",safety:["Sharps injury risk"],tips:"Air dry for MGG stain. Wet fix for Pap."},

  {id:"ihc",title:"Immunohistochemistry",intro:"IHC detects specific antigens in tissue using antibodies.",aim:"To identify cell markers and proteins.",principles:"Primary antibody binds antigen. Secondary antibody with enzyme produces color.",materials:["Primary antibody","Secondary antibody","DAB","Microscope"],procedure:["Deparaffinize","Antigen retrieval","Block","Primary Ab","Secondary","DAB","Counterstain"],result:"Brown positive staining",normal:"N/A",safety:["DAB is carcinogenic"],tips:"Always run positive and negative controls."},

  {id:"frozen",title:"Frozen Section",intro:"Rapid intraoperative diagnosis.",aim:"To provide diagnosis within 15 minutes.",principles:"Tissue is rapidly frozen and sectioned in cryostat.",materials:["Cryostat","OCT","Tissue"],procedure:["Freeze tissue","Cut 5μm section","Rapid H&E stain"],result:"Quick diagnosis",normal:"N/A",safety:["Cold burns"],tips:"Artifact is common. Not for permanent diagnosis."},

  {id:"special",title:"Special Stains - PAS",intro:"PAS stains carbohydrates and mucins.",aim:"To demonstrate glycogen and mucin.",principles:"Periodic acid oxidizes glycol to aldehyde which reacts with Schiff reagent.",materials:["PAS kit","Slides"],procedure:["Deparaffinize","Periodic acid","Schiff reagent","Counterstain"],result:"Magenta positive",normal:"N/A",safety:["Reagents"],tips:"Used for fungi and basement membrane."},

  {id:"biopsy",title:"Biopsy Handling",intro:"Proper handling of biopsy is crucial for diagnosis.",aim:"To process small tissue samples.",principles:"Same as routine but with gentle handling.",materials:["Formalin","Cassettes"],procedure:["Immediate fixation","Label properly","Process carefully"],result:"Processable tissue",normal:"N/A",safety:["Gloves"],tips:"Do not squeeze tissue with forceps."},

  {id:"reporting",title:"Histopathology Reporting",intro:"Final diagnosis based on microscopic findings.",aim:"To provide clinicopathological diagnosis.",principles:"Correlation of gross and microscopic features.",materials:["Microscope","Report form"],procedure:["Scan slide","Describe findings","Give diagnosis","Comment"],result:"Pathology report",normal:"N/A",safety:["N/A"],tips:"Correlation with clinical data improves accuracy."}
]},
{id:"bloodbank",name:"Blood Transfusion Science",analyses:[
  {id:"abo",title:"ABO Blood Grouping",intro:"ABO system classifies blood based on A and B antigens on RBCs.",aim:"To determine ABO blood group.",principles:"Antigen-antibody reaction. Cell grouping and serum grouping.",materials:["Anti-A","Anti-B","Anti-AB","Patient cells","Patient serum"],procedure:["Cell grouping: Mix cells with antisera","Serum grouping: Mix serum with A and B cells","Observe agglutination"],result:"Group A, B, AB, or O",normal:"N/A",safety:["Blood precautions"],tips:"Cell and serum grouping must agree."},

  {id:"rh",title:"Rh D Typing",intro:"Detects presence of D antigen on RBCs.",aim:"To determine Rh status.",principles:"Anti-D antibodies cause agglutination if D antigen present.",materials:["Anti-D reagent","Patient cells","Test tube"],procedure:["Add cells and Anti-D","Incubate 37°C","Centrifuge","Read"],result:"Rh Positive or Negative",normal:"N/A",safety:["Gloves"],tips:"Do weak D testing for negatives."},

  {id:"crossmatch",title:"Crossmatching",intro:"Tests compatibility between donor blood and recipient.",aim:"To prevent transfusion reaction.",principles:"Donor RBCs tested against recipient serum.",materials:["Donor cells","Recipient serum","Test tube"],procedure:["Major crossmatch","Incubate 37°C","Add Coombs","Check agglutination"],result:"Compatible or Incompatible",normal:"Compatible",safety:["BSL2"],tips:"Most important step before transfusion."},

  {id:"antibody_screen",title:"Antibody Screening",intro:"Detects irregular antibodies in recipient serum.",aim:"To screen for unexpected antibodies.",principles:"Patient serum tested against panel of known antigen cells.",materials:["Panel cells","Patient serum","Test tubes"],procedure:["Incubate serum with panel cells","Wash","Add Coombs","Read"],result:"Positive or Negative",normal:"Negative",safety:["Gloves"],tips:"3 cell panel is standard."},

  {id:"dat",title:"Direct Antiglobulin Test",intro:"Detects antibodies bound to patient RBCs.",aim:"To diagnose immune hemolytic anemia.",principles:"Coombs reagent binds to IgG or complement on RBCs.",materials:["Coombs serum","Patient RBCs"],procedure:["Wash RBCs","Add Coombs","Centrifuge","Read"],result:"Positive or Negative",normal:"Negative",safety:["Blood safety"],tips:"Positive in HDN and AIHA."},

  {id:"titer",title:"Antibody Titer",intro:"Measures strength of antibody.",aim:"To quantify antibody levels.",principles:"Serial dilution of serum tested against antigen.",materials:["Serum","Antigen cells","Test tubes"],procedure:["Make doubling dilutions","Test each","Record last positive"],result:"Titer value",normal:"N/A",safety:["PPE"],tips:"Used to monitor HDN."},

  {id:"elution",title:"Elution Technique",intro:"Removes antibody from RBC surface.",aim:"To identify antibody specificity.",principles:"Heat or chemical treatment releases antibody.",materials:["Elution kit","Sensitized RBCs"],procedure:["Heat RBCs","Centrifuge","Test eluate"],result:"Antibody identified",normal:"N/A",safety:["Heat hazard"],tips:"Used in autoantibody cases."},

  {id:"storage",title:"Blood Component Storage",intro:"Proper storage maintains blood viability.",aim:"To store blood safely.",principles:"Different components stored at different temperatures.",materials:["Blood fridge","Freezer"],procedure:["Whole blood: 2-6°C","Platelets: 22°C","FFP: -18°C"],result:"Viable blood",normal:"42 days for PRBC",safety:["Temperature monitoring"],tips:"Check fridge temperature twice daily."},

  {id:"reaction",title:"Investigation of Transfusion Reaction",intro:"Investigates suspected transfusion reaction.",aim:"To determine cause of reaction.",principles:"Repeat grouping, crossmatch, and DAT.",materials:["Post-transfusion sample","Blood bag"],procedure:["Stop transfusion","Send samples","Repeat tests","Check plasma for hemolysis"],result:"Reaction type",normal:"None",safety:["Urgent"],tips:"Most reactions are due to clerical error."},

  {id:"donor_screen",title:"Donor Blood Screening",intro:"Screens donor blood for TTIs.",aim:"To ensure safe blood.",principles:"Test for HIV, HBV, HCV, Syphilis.",materials:["Donor blood","Test kits"],procedure:["Collect sample","Test for 4 markers","Label unit"],result:"Reactive or Non-reactive",normal:"Non-reactive",safety:["BSL2"],tips:"Window period risk still exists."}
]},
    
